### ISSUE TITLE
Spurious auto generated import statements in VSCode

### ISSUE THREAD

**Issue by ancapdev** [julia-vscode/LanguageServer.jl#1000]
This has been bugging me for a while, until I tracked it down to a piece of code here. From time to time I get auto generated import statements for `Base` symbols, and it appears to stem from the completion logic. It affects the most basic symbols, `Float64` was the most recent one I hit today.

Prior to completition (during coding I rarely ever read these and only notice the imports after the fact), I see a tooltip with: 
```
This is an unexported symbol and will be explicitly imported
```
Which appears to originate here:
https://github.com/julia-vscode/LanguageServer.jl/blob/v4.1.0/src/requests/completions.jl#L185

Can this be fixed, or is there a way to disable the logic?

**Comment by pfitzseb** [comment]
Check out the `julia.completionmode` setting. `import` was the default once upon a time, but `qualify` (the current default) is much less intrusive.

**Comment by ancapdev** [comment]
Thanks a bunch, that was the setting, it was set to `import`.
