### ISSUE TITLE
Language Server throwing MethodError

### ISSUE THREAD

**Issue by jarbus** [julia-vscode/LanguageServer.jl#1003]
Julia's Language Server has worked for me in the past, but is now throwing this error after a re-install and I can't figure out what's going on. Using the latest version and currently testing without an editor so I can catch debug info.
```julia
julia> using LanguageServer, LanguageServer.SymbolServer; runserver()
[ Info: Precompiling LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7]
ERROR: MethodError: no method matching (::LanguageServer.var"#93#95"{LanguageServerInstance})(::String, ::Int64)
Closest candidates are:
  (::LanguageServer.var"#93#95")(::Any) at /home/jack/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:185
Stacktrace:
 [1] getstore(ssi::SymbolServerInstance, environment_path::String, progress_callback::LanguageServer.var"#93#95"{LanguageServerInstance}, error_handler::Nothing; download::Bool)
   @ SymbolServer ~/.julia/packages/SymbolServer/GBhfx/src/SymbolServer.jl:47
 [2] macro expansion
   @ ~/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:182 [inlined]
 [3] (::LanguageServer.var"#92#94"{LanguageServerInstance})()
   @ LanguageServer ./task.jl:411
```

**Comment by clason** [comment]
What version of Julia are you using?

**Comment by jarbus** [comment]
I'm using 1.6.3. I followed the install instructions for vim, so running

```julia
julia --startup-file=no --history-file=no -e 'ls_install_path = joinpath(get(DEPOT_PATH, 1, joinpath(homedir(), ".julia")), "environments", "nvim-lspconfig"); pushfirst!(LOAD_PATH, ls_install_path);  using LanguageServer; popfirst!(LOAD_PATH); depot_path = get(ENV, "JULIA_DEPOT_PATH", ""); project_path = let; dirname(something( Base.load_path_expand(( p = get(ENV, "JULIA_PROJECT", nothing); p === nothing ? nothing : isempty(p) ? nothing : p )), Base.current_project(), get(Base.load_path(), 1, nothing), Base.load_path_expand("@v#.#"), )) end;   @info "Running language server" VERSION pwd() project_path depot_path;    server = LanguageServer.LanguageServerInstance(stdin, stdout, project_path, depot_path);    server.runlinter = true;    run(server)'
```

**Comment by clason** [comment]
I think it would be helpful to fully state your environment:
1. julia version and platform
2. client (vim or neovim? what version? which language client)
3. minimal example (`Project.toml` for the julia package you're working on and for your global environment)
4. Exact reproducing steps (consolidated, in your issue description if you weren't using master before) together with the error message and the full log (if available).

**Comment by nchisholm** [comment]
I was getting the same error as @jarbus using `LanguageServer v4.10`.  Switching to `#master` did resolve the error for me, but I am using `julia v1.7.0rc2`.

**Comment by jarbus** [comment]
> I think it would be helpful to fully state your environment:
> 
> 1. julia version and platform
> 2. client (vim or neovim? what version? which language client)
> 3. minimal example (`Project.toml` for the julia package you're working on and for your global environment)
> 4. Exact reproducing steps (consolidated, in your issue description if you weren't using master before) together with the error message and the full log (if available).
Actually LanguageServer.jl seems to work now, I think it only crashes on scripts without an associated Project.toml file. Thanks for the help!
