### ISSUE TITLE
please add lsp-bridge support

### ISSUE THREAD

**Issue by nesteiner** [julia-vscode/LanguageServer.jl#1098]
there is a new lsp client developing: https://github.com/manateelazycat/lsp-bridge  
and I think this is really cool and fast, can you take a try and add julia lsp support ?

**Comment by fredrikekre** [comment]
I don't think any of the developers here use Emacs, so would probably require someone (maybe you) to step up and do it.

That said, what doesn't work? It looks to be just a client so I don't understand what needs to be done server side.

**Comment by pfitzseb** [comment]
Yeah, please reach out if there are any server-side issues specific to that client.
