### ISSUE TITLE
No diagnostics / new URI handling maybe faulty for Windows drive letters?

### ISSUE THREAD

**Issue by jwortmann** [julia-vscode/LanguageServer.jl#1103]
### Background

I just updated LanguageServer.jl to the latest commit 512b05add26a5d83fc2aca74a8c820c65385fd09 for the Sublime Text client (Manifest.toml temporarily [here](https://github.com/sublimelsp/LSP-julia/blob/test/server/Manifest.toml)).

### Symptoms

After the language server initializes, diagnostics are reported as expected. But as soon as you open a Julia file, the language server reports empty diagnostics for that file.

### Investigation

Just a speculation, but perhaps this may be caused by an updated URI handling in the language server (https://github.com/julia-vscode/LanguageServer.jl/commit/7b4759b7c20235ae1f98fc46de380e35534d963c)? The following seems suspicious to me:

From the JSON-RPC log I can see that the language server usually reports diagnostics with lowercase drive letter, for example `file:///d%3A/ ...`
```
:: <-  julia textDocument/publishDiagnostics: {'version': 0, 'diagnostics': [{'message': 'An argument is included in a function signature but not used within its body.', 'severity': 4, 'code': 'UnusedFunctionArgument', 'range': {'end': {'line': 0, 'character': 117}, 'start': {'line': 0, 'character': 113}}, 'source': 'Julia', 'tags': [1]}], 'uri': 'file:///d%3A/git/LanguageServer.jl/src/requests/highlight.jl'}
```

But Sublime Text uses an uppercase drive letter for the URIs, for example
```
::  -> julia textDocument/didOpen: {'textDocument': {'languageId': 'julia', 'version': 0, 'uri': 'file:///D:/git/LanguageServer.jl/src/requests/highlight.jl', 'text': 'function textDocument_documentHighlight_request(params::DocumentHighlightParams, server::LanguageServerInstance, conn)\n    doc = getdocument(server, params.textDocument.uri)\n    offset = get_offset(doc, params.position)\n    identifier = get_identifier(getcst(doc), offset)\n    identifier !== nothing || return nothing\n    highlights = DocumentHighlight[]\n    for_each_ref(identifier) do ref, doc1, o\n        if get_uri(doc1) == get_uri(doc)\n            kind = StaticLint.hasbinding(ref) ? DocumentHighlightKinds.Write : DocumentHighlightKinds.Read\n            push!(highlights, DocumentHighlight(Range(doc, o .+ (0:ref.span)), kind))\n        end\n    end\n    return isempty(highlights) ? nothing : highlights\nend\n'}}
```

After that, the language server will send back a notification with empty diagnostics for that file. Note the uppercase drive letter now, similar to what was just sent by the client:
```
:: <-  julia textDocument/publishDiagnostics: {'version': 0, 'diagnostics': [], 'uri': 'file:///D%3A/git/LanguageServer.jl/src/requests/highlight.jl'}
```

Interestingly, other requests seem to still work fine, e.g. documentHighlight, code actions etc., even though the client always uses the uppercase drive letter in its requests.

**Comment by jwortmann** [comment]
I did a little bit of debugging and can confirm that this problem was indeed introduced with 7b4759b7c20235ae1f98fc46de380e35534d963c. Before merging that PR, comparisons and hashes for `file://` URIs on Windows were made case insensitive by lowercasing the full URI in https://github.com/julia-vscode/LanguageServer.jl/blob/fccc5b8c28db94cffecf10644b45bcfdd0740dcd/src/uri2.jl#L3-L4 but this file was removed in the linked commit.

After the server initializes, it will generate URIs for the files in the workspace folders https://github.com/julia-vscode/LanguageServer.jl/blob/ddcbc1ac2cea5a096c3390273601337c823145a2/src/requests/init.jl#L104 and these URIs will use lowercased drive letters (I assume this is in order to match the URIs from VS Code which have lowercased drive letters for whatever reason): https://github.com/julia-vscode/LanguageServer.jl/blob/ddcbc1ac2cea5a096c3390273601337c823145a2/src/URIs2/uri_helpers.jl#L53

So by removing the normalization from the deleted `uri2.jl` file, some functions like https://github.com/julia-vscode/LanguageServer.jl/blob/ddcbc1ac2cea5a096c3390273601337c823145a2/src/languageserverinstance.jl#L104-L105 don't work anymore if the URIs from client requests don't exactly match what is stored in the server. And therefore diagnostics and probably some other features won't work anymore in such a case.

I guess a solution would be to re-add the case-insensitive comparison and hash functions on Windows for the new `URI` type. Bugs resulting from incompatible casing of drive letters have occured and were reported before in LSP, and apparently the conclusion was that both client and server should do normalization dependent on the file system's case sensitivity (https://github.com/microsoft/language-server-protocol/pull/1019#issuecomment-645881267).

**Comment by davidanthoff** [comment]
Thanks a lot for your detective work, super helpful!

I have a PR that adds the old code back in, and I think we should merge that short-term.

I think we could also consider a more thorough implementation, though. In that case we would normalize each incoming uri that has a file scheme and then use the normalized version as key in whatever dict. My understanding is that would be the more appropriate way to deal with this situation.
