### ISSUE TITLE
LSP workspaces.

### ISSUE THREAD

**Issue by mfiano** [julia-vscode/LanguageServer.jl#1114]
I have a rather complicated Neovim configuration that configures my `quickfix` buffer to display LSP diagnostics. With an empty Julia project and an empty base module:

```julia
module Mod

end
```

in a file `src/Mod.jl`, and also another file next to it, `foo.jl` that contains intentional syntax errors, LS.jl retrieves these diagnostics and my quickfix window is populated with them, despite the empty module above not using `include` or importing its code in any way. Switching my quickfix settings over to only pull in LSP "document" diagnostics fixes this issue for me.

I do not know enough about LSP or LS.jl to know if this should be considered a bug or a feature, but I would expect LS.jl to only know about files that are referenced in code in some way.

**Comment by fredrikekre** [comment]
You are probably thinking about https://github.com/neovim/neovim/pull/18639 which fixed caused some similar action, but this is not it.

What OP does here was to request all diagnostic for the workspace, and is asking about whether files that are not open are included in the workspace. I think they are, and that it is working as intended.

**Comment by pfitzseb** [comment]
Right, I misread that. So yes, this is indeed intentional.
