### ISSUE TITLE
JuliaFormatter.toml files not seen

### ISSUE THREAD

**Issue by mfiano** [julia-vscode/LanguageServer.jl#1115]
Juliaformatter.jl looks for `.JuliaFormatter.toml` files in the project's directory, and if not found, up the tree until it finds one. I can get this to work using JuliaFormatter manually outside of LS.jl, but LS.jl never sees any of my toml files, either in the project or anywhere up the tree.

I am using neovim with the recommended LS.jl settings (separate process/environment). That led me to try placing the toml file in the `$JULIA_DEPOT_PATH` next to the nvim-lspconfig environment, but still, it cannot see my settings.

I am not sure if I am doing something wrong or what else to try, or if this just needs some more support from LS.jl.

**Comment by pfitzseb** [comment]
This behaviour is intentional.
