### ISSUE TITLE
"hover" does not work on unqualified Base symbols

### ISSUE THREAD

**Issue by mfiano** [julia-vscode/LanguageServer.jl#1117]
In a module that implicitly uses  `Base`, "hovering" on `zeros` does not produce anything, however, it does on `Base.zeros`.

**Comment by fredrikekre** [comment]
Can't reproduce.

**Comment by mfiano** [comment]
I can't reproduce anymore it seems. It might have just been a side effect of the other issues I posted preventing my from using the last 2 releases (I'm on ddcbc1ac2cea5a096c3390273601337c823145a2 still). Closing this for now.
