### ISSUE TITLE
Warnings for EnumX and CEnum

### ISSUE THREAD

**Issue by VarLad** [julia-vscode/LanguageServer.jl#1161]
While trying out the two packages, for example
```julia
using EnumX
@enumx A begin
    a
end
```
or

```julia
using CEnum
@cenum A begin
    a
end
```
In both cases, I get the warning
`Missing reference A` `Missing reference a`

I expect it to work similarly to `@enum` where I don't get such warnings. Can this be fixed from LanguageServer.jl?

**Comment by fredrikekre** [comment]
> Can this be fixed from LanguageServer.jl?

Probably not, standard enum is special-cased, but obviously LS.jl can not be aware of all packages that introduce bindings through macros.
