### ISSUE TITLE
Missing reference for at-propagate_inbounds

### ISSUE THREAD

**Issue by fredrikekre** [julia-vscode/LanguageServer.jl#1183]
```
using Base: @propagate_inbounds     ■ Missing reference: @propagate_inbounds
@propagate_inbounds                 ■ Missing reference: @propagate_inbounds
```
I am not sure why this macro is special. Autocompletion suggested it (and automatically added the import) so the server clearly knows about it, and also knows the correct module to do the import.

**Comment by aviatesk** [comment]
Seems to be resolved in the latest extension.
