### ISSUE TITLE
Entire file gets formatted when the range refers to the top most text-block of code

### ISSUE THREAD

**Issue by mroavi** [julia-vscode/LanguageServer.jl#1187]
I'm using Neovim 0.8 together with Julia's LSP server (LanguageServer 4.3.1)

Before:
```julia
 
function hi()
println("Hi, World")
end

function hello()
println("Hello, World")
end
```

After: `:lua vim.lsp.buf.format({ range = { ['start'] = {2,0}, ['end'] = {4,0} } })`
```julia
 
function hi()
  println("Hi, World")
end

function hello()
  println("Hello, World")
end
```

Expected:
```julia
 
function hi()
  println("Hi, World")
end

function hello()
println("Hello, World")
end
```

**Comment by fredrikekre** [comment]
I am pretty sure the `do` is a red herring and this is just a version of #1184?

**Comment by mroavi** [comment]
Like in https://github.com/julia-vscode/LanguageServer.jl/issues/1180, the issue is inside the `get_inner_expr` function. In this case, it returns an expression of the entire file rather than of the range argument.

**Comment by mroavi** [comment]
I just noticed that the do-block is not what is causing the issue.

**Comment by mroavi** [comment]
> I am pretty sure the `do` is a red herring and this is just a version of #1184?

Very probable. @danielsoutar does your issue occur only when selecting the top-most block of code? In my case, if the given range encloses the `hello` function, then the formatting is done correctly.

**Comment by mroavi** [comment]
The PR above fixes this problem in the same way that @pfitzseb suggested in https://github.com/julia-vscode/LanguageServer.jl/issues/1180 but in a different if statement.

**Comment by danielsoutar** [comment]
> > I am pretty sure the `do` is a red herring and this is just a version of #1184?
> 
> Very probable. @danielsoutar does your issue occur only when selecting the top-most block of code? This is what I'm seeing. For example, if the range I pass includes only the `hello` function, then the formatting is done correctly.

I use VSCode, and for my workflow I highlight the selection, and choose 'Format selection' via the command bar. My issue was when I tried formatting across several functions. This is with a custom .JuliaFormatter.toml file, so I'd need to check with my work machine whether this applies with the default formatter.

**Comment by danielsoutar** [comment]
Apologies for cluttering this thread, but can I get an answer on how I can bring this change into my VSCode extension? Could I check out a particular version of the language server to get this change, or do I need to wait for an official release?

**Comment by mroavi** [comment]
Try asking in Slack's #vscode channel or in Julia's [Discourse](https://discourse.julialang.org/). I don't use VSCode so I really don't know.
