### ISSUE TITLE
Add Code Completion for object properties

### ISSUE THREAD

**Issue by HiramTheHero** [julia-vscode/LanguageServer.jl#1199]
In the following example:

```
julia> using RDatasets;

julia> iris = RDatasets.dataset("datasets","iris");

julia> propertynames(iris)
5-element Vector{Symbol}:
 :SepalLength
 :SepalWidth
 :PetalLength
 :PetalWidth
 :Species
```

It would be great that when I type `iris.` I would have Language Server give me a code completion list of the properties of the object.

I don't understand how the LanguageServer ecosystem really works. The most information I've found on the topic is https://github.com/julia-vscode/LanguageServer.jl/issues/734. Is something like this feasible? If so, I am more than willing to try and implement such a feature.

Not sure if this is the right place to put this feature request. I just know that it would be great to have this functionality in neovim.

Thank you for the hard work you all have put into this package.

**Comment by pfitzseb** [comment]
This isn't possible with the current LanguageServer.jl design, since the LS doesn't have access to the object itself and there's no way to statically determine the property names. A hybrid solution where we fetch these runtime completions from the REPL is possible (and indeed implemented):
![image](https://user-images.githubusercontent.com/6735977/210323211-536ef6b5-d1bf-4af5-b5da-a5d9dbe1308f.png)

**Comment by HiramTheHero** [comment]
Thank you for the information. I haven't experienced anything like this in neovim. Is this exclusively a vscode feature? Or is this functionality within another Julia package?

**Comment by pfitzseb** [comment]
> Is this exclusively a vscode feature?

Yes. We need a REPL we know how to talk to which has the object in memory.

**Comment by HiramTheHero** [comment]
Good to know. I wasn't aware of this feature, even when I was using vscode. I didn't realize I had to enable `Julia: Runtime Completions` within settings. For some reason it was off. Thanks for the information.

**Comment by phil-reyher** [comment]
Is direct object access planned? I really miss this feature in neovim and since there is no standardised way of using the REPL with vim, I reckon runtime completions won't happen?

**Comment by pfitzseb** [comment]
There currently aren't any plans for supporting runtime-computed `propertynames` in the language server directly, no.
