### ISSUE TITLE
Crash upon requesting 'window/progress' (neovim)

### ISSUE THREAD

**Issue by KMIJPH** [julia-vscode/LanguageServer.jl#1206]
The language server crashes every time I try to save a file.
I did read through a lot of the issues, but could not resolve this problem.

Log:
```
[ERROR][2023-01-24 12:48:07] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	'┌ Info: Running language server\n│   VERSION = v"1.8.0"\n│   pwd() = "/mnt/Data/Sync/Archive/scripts/julia/MyProject"\n│   project_path = "/mnt/Data/Sync/Archive/scripts/julia/MyProject"\n└   depot_path = ""\n'
[ERROR][2023-01-24 12:48:22] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	"[ Info: Received new data from Julia Symbol Server.\n"
[ERROR][2023-01-24 12:48:22] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	"ERROR: "
[ERROR][2023-01-24 12:48:23] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	"Unknown method window/progress.\nStacktrace:\n [1] dispatch_msg(x::"
[ERROR][2023-01-24 12:48:23] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	"JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::"
[ERROR][2023-01-24 12:48:23] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	"Dict{String, Any})\n   @ JSONRPC "
[ERROR][2023-01-24 12:48:23] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	"~/.julia/packages/JSONRPC/P0G1p/src/typed.jl:81\n [2] run("
[ERROR][2023-01-24 12:48:23] .../vim/lsp/rpc.lua:733	"rpc"	"julia"	"stderr"	"server::LanguageServerInstance)\n   @ LanguageServer ~/.julia/packages/LanguageServer/0vsx2/src/languageserverinstance.jl:382\n [3] top-level scope\n   @ none:31\n"
```

The file (it does crash on every file though):
```
module MyProject
greet() = print("Hello World!")
end
```

**Comment by fredrikekre** [comment]
I have never seen this. What is the version of neovim and version of LanguageServer you are using?

**Comment by KMIJPH** [comment]
NVIM v0.8.2
LanguageServer 4.3.1

I have an autocommand that formats files on save with `lsp.buf.format()`. After removing julia filetypes from the pattern, it does not crash. So there's that.

**Comment by KMIJPH** [comment]
I investigated this further and the crash seems to result from the call `vim.lsp.buf.server_ready()`.
Maybe this is something of interest?

**Comment by fredrikekre** [comment]
Who is calling that?

**Comment by KMIJPH** [comment]
No one in particular.
It is a [built-in method](https://github.com/neovim/neovim/blob/7ef5e363d360f86c5d8d403e90ed256f4de798ec/runtime/doc/lsp.txt#L1206) in neovim to check whether the lsp server is reader for a given buffer ([defined here](https://github.com/neovim/neovim/blob/bcdbf77537cec4567a334a39fd5965a3f5668a1a/runtime/lua/vim/lsp/buf.lua#L34)).
I had a hook configured to check whether the lsp-server was ready before attempting to format a buffer.

I really have no idea about the lsp protocol, so I'm not sure whether it should be addressed as a neovim problem or a problem of this particular language server.

**Comment by KMIJPH** [comment]
Or maybe put differently: should an unknown method crash the language server?

**Comment by fredrikekre** [comment]
Okay. I don't see any mentions of that method anywhere on the internet... Is it allowed to send any type of notification like that? I don't see anything about that in the spec either.

**Comment by fredrikekre** [comment]
clangd just prints "unhandled notification"

**Comment by KMIJPH** [comment]
I could not find anything in the spec either..
I will try to investigate this further on the weekend.

**Comment by fredrikekre** [comment]
I don't think you need to spend time on it, whether it should error or simply be ignored have been discussed in e.g. https://github.com/julia-vscode/LanguageServer.jl/issues/1155 and some initial work is waiting in https://github.com/julia-vscode/JSONRPC.jl/pull/71

**Comment by KMIJPH** [comment]
Okay, I see. Thank you!
