### ISSUE TITLE
const for mutable structs

### ISSUE THREAD

**Issue by filchristou** [julia-vscode/LanguageServer.jl#1208]
a quite new feature in julia is `const` in mutable structs. It looks like this is still not recognised by the julia linter.
![image](https://user-images.githubusercontent.com/27723218/218093780-b6e5d602-c520-4534-80d9-86a0ed38721f.png)

(Not entirely sure whether this issue really belongs in this repo)

**Comment by pfitzseb** [comment]
This is supported now.
