### ISSUE TITLE
`Missing reference` for unexported Base symbols

### ISSUE THREAD

**Issue by simonmandlik** [julia-vscode/LanguageServer.jl#1230]
If `Base` defines a symbol, but doesn't export it, importing it with `using` is a valid command. But Language Server yields a warning

<img width="598" alt="image" src="https://github.com/julia-vscode/LanguageServer.jl/assets/16707112/8e0c39bd-9b14-463a-9cee-6b68d6cd1f79">

Here, `AbstractVecOrTuple` and `CodeUnits` are from `Base`, but are not exported.

LS produces a false positive warning. If importing unexported stuff from modules is a bad practice, shouldn't the Warning say something different?

Maybe related to https://github.com/julia-vscode/LanguageServer.jl/issues/1204 and https://github.com/julia-vscode/LanguageServer.jl/issues/1197

**Comment by aviatesk** [comment]
Looks like this seems to be working on the latest release.
