### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by aloispichler** [julia-vscode/LanguageServer.jl#1231]
I am on nvim and trying to install julia-ls with Lazy. The result is below. Any help appreciated.
Failed
    ◍ julia-lsp
      ▼ Displaying full log
        Downloading file "https://github.com/mason-org/julia-lsp/releases/download/v1.47.2/julia-lsp-v1.47.2.zip"…
        Unpacking "julia-lsp-v1.47.2.zip"…
        spawn: unzip failed with exit code - and signal -. unzip is not executable

**Comment by pfitzseb** [comment]
Seems like you should report this to https://github.com/mason-org/julia-lsp.
