### ISSUE TITLE
Base Standard Library modules don't load, no autocomplete and no messages on hover

### ISSUE THREAD

**Issue by raythurnevoid** [julia-vscode/LanguageServer.jl#1235]
![image](https://github.com/julia-vscode/LanguageServer.jl/assets/53383860/5bb1f3bb-2054-415e-b2e3-9d7162cebe50)
![image](https://github.com/julia-vscode/LanguageServer.jl/assets/53383860/d4a918d6-13d2-4ddb-aba4-10722c433974)

This is my `Project.toml`
```
name = "maui_git_stats_jl"
uuid = "eab06994-3655-4b8c-82cc-e2ff5ee1fd2f"
version = "0.1.0"

```

The REPL works fine.

The only modules I see are:
![image](https://github.com/julia-vscode/LanguageServer.jl/assets/53383860/9e4a723d-3601-4bb1-b09a-1a4059bb038c)

Julia version: 1.9.3
Windows 11

**Comment by pfitzseb** [comment]
Standard libraries need to be in your Package.toml too.

**Comment by raythurnevoid** [comment]
Yes i've added Dates with `pkg> add Dates` and it works now. Thanks!

Perhaps this should be specified somewhere, because apparently everything works fine for Julia but not for the extension.

**Comment by pfitzseb** [comment]
It only works fine in interactive contexts, I think.
