### ISSUE TITLE
`Base.@kwdef struct...` works, `using Base: @kwdef; @kwdef struct...` doesn't

### ISSUE THREAD

**Issue by dhanak** [julia-vscode/LanguageServer.jl#1259]
When I have

```jl
Base.@kwdef struct MyStruct
   field::Int = 0
end
```

everything works as expected.

But when I have

```jl
using Base: @kwdef
@kwdef struct MyStruct
   field::Int = 0
end
```

then I get errors at the `using` declaration (`Julia: Missing reference: @kwdef`), and also inside the struct (`Julia: Missing reference; field`). Can this be resolved easily (without having to use `Base.@kwdef`)?

**Comment by pfitzseb** [comment]
Hm, weird, this works fine for me:
![image](https://github.com/julia-vscode/LanguageServer.jl/assets/6735977/264307f6-0d1b-4382-96b8-07e818bfb7b0)

What version of LanguageServer/Julia/the VS Code extension are you on?

**Comment by dhanak** [comment]
Sorry, I forgot to add that I'm using Emacs v28.2, with `eglot-1.15` and `eglot-jl-20230601.1335`. Maybe it isn't a LanguageServer specific thing then? I assumed that the `eglot-jl` is just a very thin wrapper around LS, but perhaps not.

![image](https://github.com/julia-vscode/LanguageServer.jl/assets/55064/919976c8-67e7-44b1-9f96-0e768fcda295)

Odd. I also noticed that as I type in the buffer, the error underline disappears and reappears seemingly randomly, but when I save, it reappears reliably.

**Comment by dhanak** [comment]
Also:

```
  [2b0e0bc5] LanguageServer v4.4.0
  [cf896787] SymbolServer v7.2.1
```

**Comment by pfitzseb** [comment]
Can you still repro this? LanguageServer and StaticLint got updated some time earlier this year.
