### ISSUE TITLE
"Missing Reference" warning false positive when `using` package while running file in global environment

### ISSUE THREAD

**Issue by j-adel** [julia-vscode/LanguageServer.jl#1276]
It’s really easy to reproduce. Simply creating a new Julia file and having a `using Example` (where Example is an added package in the global environment), the linter will show a warning underlining Example and any functions from it stating “Missing Reference”. Furthermore, any functions from `Example` are recognized so no linter features work with it. Running the REPL runs the code just fine. Here is further discussion of this issue and a reproduction of it: https://discourse.julialang.org/t/missing-reference-warnings-with-julia-in-vs-code/31321/22?u=j-adel
I remember this used to work some time ago. Adding a Project.toml and adding `Example` to the local environment fixes it. However I think the linter is supposed to detect the global environment when it's there.

**Comment by dhanak** [comment]
I'm just guessing, but this could be related to #988.

**Comment by aviatesk** [comment]
yeah, this is a dup of #988 .
