### ISSUE TITLE
[Security/Integrity Issue] Cached Code Execution in VSCode Tests

### ISSUE THREAD

**Issue by MilesCranmer** [julia-vscode/LanguageServer.jl#1333]
x-posting https://github.com/julia-vscode/TestItemRunner.jl/issues/97 @davidanthoff @pfitzseb @kenahoo

I noticed that sometimes (on both 1.10.7 and 1.11.2), I will:

1. Run a `@testitem` test in VSCode.
2. Observe the test to fail.
3. Modify the code and re-run the test.
4. Observe the test to fail.
5. Inspect the error, and realise that TestItemRunner.jl is **running some cached version of the code from before my edits.**

This happens even if I manually check, from shell, that the current test file is in fact correct (and I didn't forget to save it or something silly).

This is problematic behavior and I'm not really sure what to do. It also seems a bit risky for things like arbitrary code execution, since it seems to execute code stored in some external location – is the cache accessible to other processes? How can I ensure that the LS is running the code I have written? I guess I just don't really understand where LS.jl is putting my code, or how to see what it's actually executing.

I also haven't really been able to figure out the pattern for when this occurs. When it does occur, I find sometimes a combination of re-editing the test with random edits, like print statements, or commenting out lines, will be enough to tell TestItemRunner.jl that it needs to update the code on the next run.

Here's an example of what I mean: ![Image](https://github.com/user-attachments/assets/4651aa88-1ecf-4d1c-b1c2-beee403bb594)

^As you can see, `safe_atanh` is indeed imported. But the test runner tells me there's an import error. I can run this test fine in my REPL and in `Pkg.test()`; it's just the LS somehow is caching things. Even if I reload VSCode, I get the same error. At some point after something happens, the test will finally get updated. But I have no idea what triggers the cache to flush.

In case it helps, I have noticed that this issue occurs more frequently with large test suites. Not sure if that points to the problem or not.

What is the next step to debug this?

**Comment by davidanthoff** [comment]
I'm closing this issue as a duplicate of https://github.com/julia-vscode/TestItemRunner.jl/issues/97.
