### ISSUE TITLE
Document arguments for LanguageServerInstance

### ISSUE THREAD

**Issue by gdkrmr** [julia-vscode/LanguageServer.jl#310]
I've tried to make emacs' `lsp-julia` use the new `LanguageServer` for Julia 1.0 but failed, because the call to `LanguageServerInstance` now has more arguments and I cannot quite figure out what they are. Could you please document them!

**Comment by benneti** [comment]
I tried it , too.
Using two emty strings and an empty dict and converting stdin and stdout to lowercase I believe the server starts but is not able to connect.
Another thing is that the launch script was not updated, to support the new parameters and I don't really get what it expects to function correctly.

**Comment by gdkrmr** [comment]
My best guess is this, `depot_path` cannot be `Array{String}`:
```julia
julia> LanguageServer.LanguageServerInstance(stdin, stdout, false, "path to package", DEPOT_PATH[1], Dict())
```

**Comment by davidanthoff** [comment]
The 4th arg has to be a path to an environment, so e.g. ``~/.julia/environments/v1.0``. The 5th arg needs to point to the julia depot you want to use, I believe an empty string should be ok there.

**Comment by non-Jedi** [comment]
Questions I still have on this before I can make a PR with better documentation:

1. How does one pass multiple depots to the `LanguageServerInstance`?
2. What depot(s) does the language server use if the `depot_path` is an empty string?
3. What environment does the language server use if the `env_path` is empty?
4. What is the purpose of passing an empty `Dict` to the `LanguageServerInstance`, and what effect would passing a non-empty `Dict` have?

As best I can tell the answers are probably in SymbolServer.jl, but I don't have time at the moment to dig through that package and find them.

**Comment by davidanthoff** [comment]
> How does one pass multiple depots to the LanguageServerInstance

Not supported, I'm afraid.

> What depot(s) does the language server use if the depot_path is an empty string?

Hopefully it will use the default depot, but I haven't really tested that scenario (because the VS Code extension always passes a path).

> What environment does the language server use if the env_path is empty?

Again, I'm actually not sure, because the VS Code extension always passes one...

> What is the purpose of passing an empty Dict

I think we should probably have defined that field as `Union{Dict,Nothing}` and initialized it as `nothing` instead of the current code, but I'm not 100% sure, @ZacLN probably knows better.

**Comment by non-Jedi** [comment]
> > How does one pass multiple depots to the LanguageServerInstance
> 
> Not supported, I'm afraid.

So this means that one has to choose between using the standard libraries which are in the `/usr/share/julia` (or similar) depot or user-installed packages in `~/.julia`. Except when passing an empty string at least it works with both. Does the empty string for that argument have special behavior, or is the standard library depot included implicitly?

**Comment by davidanthoff** [comment]
Actually, I think I was wrong :) The string you pass there as the depot is then used to set the `JULIA_DEPOT_PATH` env variable for the symbol server process. The docs [here](https://docs.julialang.org/en/latest/manual/environment-variables/#JULIA_DEPOT_PATH-1) explain how you can set that to include multiple depots!
