### ISSUE TITLE
false positive importing relative modules

### ISSUE THREAD

**Issue by gdkrmr** [julia-vscode/LanguageServer.jl#313]
LanguageServer does not find `SubMod1` in `t2.jl`, it finds `MyPkg` though.

```
MyPkg
├── Manifest.toml
├── Project.toml
└── src
    ├── MyPkg.jl
    ├── t1.jl
    └── t2.jl
```

MyPkg.jl:
```
module MyPkg
g(x) = 2 + x
include("t1.jl")
include("t2.jl")
end
```

t1.jl:
```
module SubMod1
f(x) = x^2
end
```

t2.jl:
```
module SubMod2
import ...MyPkg
import ..SubMod1
f2(x) = MyPkg.g(x) * SubMod1.f(x)
end
```

**Comment by ZacLN** [comment]
I can't replicate this

**Comment by gdkrmr** [comment]
a) It is emacs and LanguageServer is run as:

```julia
using LanguageServer, Sockets, SymbolServer;
server = LanguageServer.LanguageServerInstance(
        stdin, stdout, false,
        "/path/to/MyPkg", "",
        Dict()
);
server.runlinter = true;
run(server);
```

b) When everything is in a single file everything looks fine.

**Comment by YcWung** [comment]
Then maybe it is a problem of lsp-julia. Do you use this version [https://github.com/non-Jedi/lsp-julia](https://github.com/non-Jedi/lsp-julia) ?

**Comment by gdkrmr** [comment]
yes, latest master with some modifications for the new `LanguageServer` version (https://github.com/non-Jedi/lsp-julia/issues/3#issuecomment-439646140). The actual call script to start `LanguageServer` is in my previous comment.

**Comment by gdkrmr** [comment]
Just thinking: it may be #316, because I never rand `Pkg.dev("path/to/MyPkg")`, I simply activated the environment.

**Comment by davidanthoff** [comment]
I'm moving this to the backlog. Not because it isn't a bug, but we need to ship eventually :)
