### ISSUE TITLE
false negative

### ISSUE THREAD

**Issue by gdkrmr** [julia-vscode/LanguageServer.jl#326]
often I transform something like
```julia
f(x) = g(x)
```
into something like
```julia
function f(x) =
  g(x)
  h(x)
end
```
leaving the `=`-sign around, which does not get flagged.

**Comment by ZacLN** [comment]
fix: https://github.com/julia-vscode/CSTParser.jl/commit/7ce09b469f840cd5e39e7f64f3b066660b2be532
