### ISSUE TITLE
feature request - standalone command for invoking languageserver

### ISSUE THREAD

**Issue by sbromberger** [julia-vscode/LanguageServer.jl#337]
c.f. https://github.com/w0rp/ale/issues/2205#issuecomment-481857046

LanguageServer.jl's API changed recently which necessitates a change to any code that invokes it (here, the w0rp/ale vim plugin). It would be nice if there were a standalone script that would launch the languageserver with a more stable API (that could use sensible defaults and change them when the API changed, perhaps?) that could be called by editors.

Failing that, support for w0rp/ale would be a big win.

**Comment by ZacLN** [comment]
Defaults have been added so that you only need to provide the in/out pipes to get an instance running - is this enough for this?

Secondly, what is needed to support w0rp/ale ?

**Comment by sbromberger** [comment]
> Secondly, what is needed to support w0rp/ale ?

I don't know. I can't get the `languageserver.vim` script to run. cc @w0rp for some guidance.

**Comment by non-Jedi** [comment]
This actually already exists. The script could use a cleanup to allow selecting environment, but it's basically there.

https://github.com/julia-vscode/LanguageServer.jl/blob/master/contrib/languageserver.sh

**Comment by davidanthoff** [comment]
Cool, then I'll close this issue :)
