### ISSUE TITLE
imports of variables from module inside module not correctly handled

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/LanguageServer.jl#338]
`LanguageServer.jl` flags the following line incorrectly

```julia
import Gadfly.Geom: line, point, ribbon, render, element_aesthetics
```

I get back from the language server an event flagging each variable (line, point, ribbon, etc.) with e.g.:

```
severity: 2
code: Missing variable
source: Julia language server
message: Use of possibly undeclared variable: element_aesthetics
```
LanguageServer 0.5.1, StaticLint 0.1.1, SymbolServer 0.1.3

**Comment by ZacLN** [comment]
Fixed on master: 
![image](https://user-images.githubusercontent.com/5861046/59469259-36c38800-8e2c-11e9-8b60-02dc803a728c.png)
