### ISSUE TITLE
"textDocument/definition" from eglot can crash language server

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/LanguageServer.jl#339]
Sometimes when editing a Julia file in emacs using [eglot](https://github.com/joaotavora/eglot), `LanguageServer.jl` crashes when I invoke the goto definition functionality (or renaming a symbol). The stack-trace in stderr is:

```julia
ERROR: LoadError: MethodError: no method matching LanguageServer.TextDocumentPositionParams(::Nothing)
Closest candidates are:
  LanguageServer.TextDocumentPositionParams(::Any, !Matched::Any) at /home/adam/.julia/packages/LanguageServer/GNDpW/src/protocol/document.jl:18
  LanguageServer.TextDocumentPositionParams(!Matched::LanguageServer.TextDocumentIdentifier, !Matched::LanguageServer.Position) at /home/adam/.julia/packages/LanguageServer/GNDpW/src/protocol/document.jl:18
  LanguageServer.TextDocumentPositionParams(!Matched::Dict) at /home/adam/.julia/packages/LanguageServer/GNDpW/src/protocol/protocol.jl:25
Stacktrace:
 [1] parse_params(::Type{Val{Symbol("textDocument/definition")}}, ::Nothing) at /home/adam/.julia/packages/LanguageServer/GNDpW/src/requests/textDocument.jl:513
 [2] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at /home/adam/.julia/packages/LanguageServer/GNDpW/src/jsonrpc.jl:38
 [3] run(::LanguageServerInstance) at /home/adam/.julia/packages/LanguageServer/GNDpW/src/languageserverinstance.jl:44
 [4] top-level scope at none:0
in expression starting at /home/adam/.emacs.d/lisp/eglot-julia/eglot.jl:9
```

The content of `eglot.jl` [is described in the wiki](https://github.com/JuliaEditorSupport/LanguageServer.jl/wiki/Emacs).

**Comment by ZacLN** [comment]
I think this is an issue with the client package: null or nothing is not an acceptable parameter for eglot to send with a  "textDocument/definition" request

**Comment by non-Jedi** [comment]
Maybe so; I'd like to trigger this again, so I can have what's actually sent to report the bug to eglot. But from a language server design perspective, should bad input *ever* crash the server? Postel's law and all that.

**Comment by non-Jedi** [comment]
I haven't seen this again in the past couple months, so I'm going to assume it's been magically fixed somehow and close this issue. If anyone else is running into it or it happens again and I'm able to capture the relevant rpc, we can re-open.
