### ISSUE TITLE
filepath2uri fails for untitled files

### ISSUE THREAD

**Issue by ZacLN** [julia-vscode/LanguageServer.jl#343]
When responding to `Request`s for unsaved files we return `file://Untitled-1` rather than `untitled:Untitled-1`

**Comment by davidanthoff** [comment]
Not clear what the status here is. I'm putting it on the v0.6.0 milestone for now, but the right option might well be to just close this if this is no longer an issue.

**Comment by ZacLN** [comment]
Moving this to backlog, I've avoided this by trying to reference Document objects within LanguageServer rather than using their path. PR: https://github.com/julia-vscode/LanguageServer.jl/commit/eb360b72dbdf4133be475ffb476029d678c79d37

**Comment by ZacLN** [comment]
This seems fixed
