### ISSUE TITLE
Variables / types defined inside a module are marked as unknown

### ISSUE THREAD

**Issue by ronisbr** [julia-vscode/LanguageServer.jl#345]
Hi!

Let's say I have a module called `Testing` and in the main file `Testing.jl` I defined a variable like:

```julia
const test = 1
```

Then, in this same file, I include another one: `other.jl`. If I open `other.jl` and type `test`, then it is being marked as unknown.

Moreover, if I import something in `Testing.jl`, like `using PyPlot`, those functions are not imported by the language server when I am editing `other.jl`. Thus, `plot` is marked as unknown also.

Is it the expected behavior or am I doing something wrong?

**Comment by ronisbr** [comment]
By the way, I am using Julia 1.1 and Neovim v0.3.5 and the `master` of all Julia packages related to LanguageServer.

**Comment by ZacLN** [comment]
Hi, could you try this again with the latest masters for LanguageServer, CSTParser, Tokenize, StaticLint and SymbolServer?

**Comment by ronisbr** [comment]
Hi @ZacLN ,

For some reason, using the latest version, Julia server is being killed after every buffer modification. I am still trying to debug it.

**Comment by ronisbr** [comment]
Here is what happening. Note that as soon as I change `a` to `b`, the server crashed. I have no idea how to debug it, any tips?

![lc-bug1](https://user-images.githubusercontent.com/1068295/59553064-054ed780-8f66-11e9-8996-2dce24801098.gif)

**Comment by ronisbr** [comment]
I did some research, and the last commit that it was possible to run without this problem was 9ad598a.

**Comment by ZacLN** [comment]
Hi, is it possible to turn on the server logs (before you modify the buffer). If you can’t do this using the command in nvim you will have to ensure he language server instance used my nvim is launched with debug_mode set to true

**Comment by ronisbr** [comment]
I am trying to do this without luck. Can you help me?

**Comment by ZacLN** [comment]
Changing `debug_mode` to `true` on line 21 of `languageserverinstance.jl` should do the trick

**Comment by ZacLN** [comment]
Could you post the server logs from the crash? I'll be more easily able to work out whats going on

**Comment by ronisbr** [comment]
Sorry @ZacLN! I had a problem with my computer and I had to format everything. I am still configuring everything. I will submit the log very soon.

**Comment by ronisbr** [comment]
@ZacLN 

First I needed to modify the debugging code because I was not able to get the log. Hence, I changed the following lines at the end of `read_transport_layer`:

```julia
    f = open("/Users/ronan.arraes/log.txt", "a")
    debug_mode && write(f,"RECEIVED: $message_str\n")
    debug_mode && write(f,"\n")
    close(f)
```

and those at the end of `write_transport_layer`:

```julia
    f = open("/Users/ronan.arraes/log.txt", "a")
    debug_mode && write(f,"SENT: $response\n")
    debug_mode && write(f,string("TIME:", round(time()-T, sigdigits = 2),"\n\n"))
    close(f)
```

The log I obtained was:

```
RECEIVED: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":33678,"rootPath":"/Users/ronan.arraes/.nvim","rootUri":"file:///Users/ronan.arraes/.nvim","initializationOptions":null,"capabilities":{"workspace":{"applyEdit":true},"textDocument":{"completion":{"completionItem":{"snippetSupport":true}}}},"trace":"off"}}

SENT: {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["("]},"definitionProvider":true,"typeDefinitionProvider":false,"implementationProvider":false,"referencesProvider":true,"documentHighlightProvider":false,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":false,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"renameProvider":true,"colorProvider":false,"executeCommandProvider":{"commands":[]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":null}}}
TIME:1.2

RECEIVED: {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}

RECEIVED: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/ronan.arraes/.nvim/teste.jl","languageId":"julia","version":1,"text":"function teste\n    a = 2\nend\n\n"}}}

SENT: {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/ronan.arraes/.nvim/teste.jl","diagnostics":[]},"jsonrpc":"2.0"}
TIME:8.0

RECEIVED: {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/ronan.arraes/.nvim/teste.jl","version":2},"contentChanges":[{"text":"function teste\n    a = c\nend\n\n"}]}}
```

Does it help?

**Comment by ZacLN** [comment]
Thats super. I think the language server was telling nvim to use incremental document updates but the nvim plugin doesn't support it. https://github.com/julia-vscode/LanguageServer.jl/commit/3887b8c8d50baa7be09d68d2ab0e81418267ab4e should fix it

**Comment by ronisbr** [comment]
Hi @ZacLN , it is working perfectly now! Thanks!!
