### ISSUE TITLE
Macros names are marking as undeclared variables

### ISSUE THREAD

**Issue by ronisbr** [julia-vscode/LanguageServer.jl#346]
Every time I have a macro, its name is marked as unknown like in:

<img width="621" alt="Captura de Tela 2019-06-06 às 13 54 19" src="https://user-images.githubusercontent.com/1068295/59051211-ac46bb80-8862-11e9-91fa-31c60479ae48.png">

I am using Julia 1.1 and Neovim v0.3.5.

**Comment by ZacLN** [comment]
Fixed on master
