### ISSUE TITLE
Revisit fix for #357

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#365]
The fix for https://github.com/julia-vscode/LanguageServer.jl/issues/357 looks a little wonky to me, maybe there is some way to solve this that doesn't involve custom messages? I would have thought that the base LS protocol is rich enough to handle all such cases?

**Comment by ZacLN** [comment]
It's very much a bodge but there doesn't seem to be a native way to request a full update of a document's text. Some recent fixes should reduce the frequency that the client/server documents get out of sync
