### ISSUE TITLE
splitdrive problem

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#373]
There is still a bug there, details [here](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22%3A%22a4faebd1-aaae-11e9-aa6e-77fdfec6782e%22%2C%22timestamp%22%3A%222019-07-20T05%3A24%3A12.235Z%22%2C%22cacheId%22%3A%229c12e6a8-a955-487b-b79f-c224735e97dc%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A172800000%2C%22endTime%22%3A%222019-07-20T17%3A18%3A00.000Z%22%2C%22createdTime%22%3A%222019-07-20T17%3A18%3A46.380Z%22%2C%22isInitialTime%22%3Afalse%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D%7D/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D).

**Comment by ZacLN** [comment]
The azure details have disappeared, can we assume this is fixed?

**Comment by davidanthoff** [comment]
Yeah, if not, it will show up again in our crash reports.
