### ISSUE TITLE
Missing reference: __source__, __module__ inside macro definition

### ISSUE THREAD

**Issue by williamcol3** [julia-vscode/LanguageServer.jl#379]
When defining a macro references to either "__source__" or "__module__" will be linted as "Missing reference". As far as I know, these variable are always available within a macro definition.

Example:
![macro_bug](https://user-images.githubusercontent.com/6266711/62828359-f5402680-bba9-11e9-9735-bfa8879c6290.png)

Another example of this type of problem is module Main. As far as I know, during code execution the Main module object is always available, but the language server reports a Missing reference.

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/StaticLint.jl/commit/ec832e12f57329b5c2b8d391c4e545e91d875478

The fix for `Main` is slightly more involved
