### ISSUE TITLE
Can't get LSP to run

### ISSUE THREAD

**Issue by Sheemon7** [julia-vscode/LanguageServer.jl#392]
Hi, I apologize for a newbie question, this is my first time working with LSPs.

After running 

```
julia --startup-file=no --history-file=no -e '
    using LanguageServer;
    using Pkg;
    import StaticLint;
    import SymbolServer;
    env_path = dirname(Pkg.Types.Context().env.project_file);
    debug = true; 
    server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, "", Dict());
    server.runlinter = true;
    run(server);
'
```

the server starts,

```
[ Info: Started symbol server
[ Info: store set
```

however sending any JSON messages to the server fails. For instance, the example from wiki

```
{"jsonrpc":"2.0","id":24,"method":"julia/reload-modules","params":null}
```

ends with the following error:

```
ERROR: KeyError: key "Content-Length" not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] read_transport_layer(::Base.TTY, ::Bool) at /home/simon/.julia/packages/LanguageServer/j2G4Z/src/languageserverinstance.jl:73
 [3] run(::LanguageServerInstance) at /home/simon/.julia/packages/LanguageServer/j2G4Z/src/languageserverinstance.jl:40
 [4] top-level scope at none:0
```

Obviously, I'm doing something wrong. How do I get Language Server to run properly?

I'm running on 1.1.0, LanguageServer v0.6.1, SymbolServer v0.2.4 and StaticLint v0.2.2.

**Comment by davidanthoff** [comment]
Are you following the Base protocol described [here](https://microsoft.github.io/language-server-protocol/specification)? It sounds a bit as if you are not sending the header part there?

**Comment by Sheemon7** [comment]
Yeah, that was the problem. Thanks for help!
