### ISSUE TITLE
Sanity check: Julia v1.3.0-rc3 introduces breaking changes?

### ISSUE THREAD

**Issue by wsphillips** [julia-vscode/LanguageServer.jl#397]
I don't expect full support for non-stable Julia builds, but I want to be sure that v1.3.0-rc3 is indeed _not_ yet usable with the language server.

At present v1.2.0 works fine across three different dev setups I have (Ubuntu 18.04.3, Fedora 30, CentOS 8.0), while v1.3.0-rc3 crashes the language server regardless of the usual bugs mentioned here so far (and regardless of whether its a pre-packaged binary or built locally)

Assuming v1.3.0 is introducing breaking changes, is there any timeline on a fix? Is it something in Base or within LanguageServer.jl?

**Comment by davidanthoff** [comment]
No timeline, hopefully soon :) Both @ZacLN and I have been pretty busy with other stuff, so not too much has happened on the LS or VS Code front...

**Comment by davidanthoff** [comment]
As far as I can tell current `master` works on 1.3, so I'm closing this. If specific issues come up, please open a new issue!
