### ISSUE TITLE
Incorrect "Missing reference" when destructuring typed tuple function parameters

### ISSUE THREAD

**Issue by makedin** [julia-vscode/LanguageServer.jl#404]
The following code produces "Missing reference" warnings for symbols ```b``` and ```c```, which doesn't seem to make much sense. 

```julia
function adder(a::Int, (b, c)::Tuple{Int, Int})
  a + b + c
end
```
The Language Server sends the following messages:
```json
{"line":0,"character":25}},"severity":2,"code":"Julia","source":"Julia","message":"Missing reference: b","relatedInformation":null},{"range":{"start":{"line":0,"character":27},"end":
{"line":0,"character":28}},"severity":2,"code":"Julia","source":"Julia","message":"Missing reference: c","relatedInformation":null},{"range":{"start":{"line":1,"character":6},"end":
{"line":1,"character":7}},"severity":2,"code":"Julia","source":"Julia","message":"Missing reference: b","relatedInformation":null},{"range":{"start":{"line":1,"character":10},"end":
{"line":1,"character":11}},"severity":2,"code":"Julia","source":"Julia","message":"Missing reference: c","relatedInformation":null}]},"jsonrpc":"2.0"}
```

These warnings go away if the tuple's type definition is removed *or* if ```b``` and ```c``` are given default values.

It seems that the problem may lie with [StaticLint.jl](https://github.com/julia-vscode/StaticLint.jl) so maybe this is actually an upstream bug?

I have only tested this using [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) as a client. My Julia version is 1.2.0, LanguageServer is v0.6.1, SymbolServer is v0.2.5 and StaticLint is v0.2.2.

**Comment by ZacLN** [comment]
fix: https://github.com/julia-vscode/StaticLint.jl/commit/d7243ee533b0c5804222ed56ea8d124756d15a15
