### ISSUE TITLE
server stuck in "Tried to load PACKAGENAME but failed to load from disc, re-caching." loop

### ISSUE THREAD

**Issue by orialb** [julia-vscode/LanguageServer.jl#411]
Hi,

I just tried using the latest master to enjoy some of the recent fixes and I can't get the server to run. 
I first add the latest master in a clean environment and then run the following in the REPL:
```julia
using LanguageServer
server = LanguageServerInstance(stdin, stdout, true, ".", "", Dict())
run(server) 
```

Afterwards the server gets stuck in an infinite loop of trying t load packages from disc:
```julia
[ Info: Started symbol server
[ Info: Tried to load LanguageServer but failed to load from disc, re-caching.
[ Info: Tried to load Dates but failed to load from disc, re-caching.
[ Info: Tried to load StaticLint but failed to load from disc, re-caching.
[ Info: Tried to load Parsers but failed to load from disc, re-caching.
[ Info: Tried to load CSTParser but failed to load from disc, re-caching.
[ Info: Tried to load SHA but failed to load from disc, re-caching.
[ Info: Tried to load Sockets but failed to load from disc, re-caching.
[ Info: Tried to load Random but failed to load from disc, re-caching.
....
```
(this also happens if I use `server = LanguageServerInstance(stdin, stdout, true, "/Users/USERNAME/.julia/environments/v1.1", "", Dict())` )

Julia version:
```julia
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```
(tried also with Julia 1.2) 

Any ideas how to fix / debug this? Is there some cache I should try deleting?

**Comment by orialb** [comment]
I tried to delete the cache in the `store` folder of the relevant `.julia/packages/SymbolServer/` folder, but this didn't help.

**Comment by orialb** [comment]
Never mind, I updated `SymbolServer` to master instead of the version specified in `LangaugeServer` and it works now.

**Comment by AmjadHD** [comment]
Yesterday I downloaded v1.3 of julia and installed LanguageServer.jl v1.0, and this still happens.

**Comment by AmjadHD** [comment]
Anyone seeing this ? @ZacLN ?

**Comment by ZacLN** [comment]
Have you tried loading SymbolServer into the same scope that you load LanguageServer?

**Comment by AmjadHD** [comment]
No, here's a preview of the command in the julia prompt:
![image](https://user-images.githubusercontent.com/33235928/70990250-68f8bf80-20c5-11ea-97f0-90fbb5c9320c.png)

**Comment by AmjadHD** [comment]
> Have you tried loading SymbolServer into the same scope that you load LanguageServer?

How do I do this ? via `using SymbolServer` ?

**Comment by ZacLN** [comment]
Yep, in your code above use `using LanguageServer, SymbolServer`. Its unclear why but it seems to be necessary

**Comment by AmjadHD** [comment]
```julia
julia> using LanguageServer, SymbolServer
ERROR: ArgumentError: Package SymbolServer not found in current path:
- Run `import Pkg; Pkg.add("SymbolServer")` to install the SymbolServer package.

Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:887
```

**Comment by AmjadHD** [comment]
should i `add` it ?

**Comment by ZacLN** [comment]
Yes that or you can do `using LanguageServer, LanguageServer.SymbolServer`

**Comment by AmjadHD** [comment]
Thanks it worked now, you should upfate the readme.
