### ISSUE TITLE
relatedInformation should be an empty array instead of 'null'

### ISSUE THREAD

**Issue by DRiKE** [julia-vscode/LanguageServer.jl#415]
If I understand the specification ([version 3.14](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/)) correctly, the `relatedInformation` in a response is optional, but it is always an array. Currently, the language server responds with `null`, on which my vim+ale errors. A quick and dirty fix like below seems to work, but given that the relatedInformation field in the Diagnostic struct is `Union{Nothing,Vector{_}}`, maybe more changes are necessary.

Versions:
Julia 1.2.0
LanguageServer.jl v1.0.1-DEV (HEAD I think, I did `]dev LanguageServer`)
vim 8.1 with ALE HEAD (2d9380d)

```
diff --git a/src/parsing.jl b/src/parsing.jl
index e24ef5d..620f395 100644
--- a/src/parsing.jl
+++ b/src/parsing.jl
@@ -48,17 +48,17 @@ function mark_errors(doc, out = Diagnostic[])
                     offset += errs[i][2].span
                 else
                     if errs[i][2].typ === CSTParser.IDENTIFIER
-                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Missing reference: $(errs[i][2].val)", nothing))
+                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Missing reference: $(errs[i][2].val)", []))
                     elseif errs[i][2].typ === CSTParser.ErrorToken
-                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 1, "Julia", "Julia", "Parsing error", nothing))
+                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 1, "Julia", "Julia", "Parsing error", []))
                     elseif errs[i][2].ref == StaticLint.IncorrectCallNargs
-                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Incorrect number of arguments", nothing))
+                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Incorrect number of arguments", []))
                     elseif errs[i][2].ref == StaticLint.IncorrectIterSpec
-                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Incorrect specification for iterator", nothing))
+                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Incorrect specification for iterator", []))
                     elseif errs[i][2].ref == StaticLint.NothingEquality
-                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Compare against `nothing` using === ", nothing))
+                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Compare against `[]` using === ", []))
                      elseif errs[i][2].ref == StaticLint.NothingNotEq
-                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Compare against `nothing` using !== ", nothing))
+                        push!(out, Diagnostic(Range(r[1] - 1, r[2], line - 1, char), 2, "Julia", "Julia", "Compare against `[]` using !== ", []))
                     end
                     i += 1
                     i>n && break
```

**Comment by ZacLN** [comment]
@davidanthoff, I think this sort of thing must be pretty prevalent across our entire Language Server implementation (i.e. we put `nothing` into optional fields` when we don't want to fill them). 

Do we need to change the general approach to handling optional fields. I wouldn't want to allocate loads of empty arrays (as above) as a solution. A proper approach would possibly involve using `Missing` in our implementation of the protocol and having the jsonifying function ignore missing fields.

**Comment by davidanthoff** [comment]
Yes, we should find a way to just leave these fields out. `missing` seems like a good idea, because we can't use `nothing` because we sometimes actually need to emit a `null` value, right?

**Comment by ZacLN** [comment]
Exactly

**Comment by davidanthoff** [comment]
Also see my lame attempt to fix this in one specific case https://github.com/julia-vscode/LanguageServer.jl/pull/416/files :) A general story would be much nicer.

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/LanguageServer.jl/pull/430 attempts to fix this more generally!

**Comment by davidanthoff** [comment]
Closing because we have a PR tracking this.
