### ISSUE TITLE
workspace/configuration sends out-of-spec message

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/LanguageServer.jl#418]
Per discussion in https://github.com/julia-vscode/LanguageServer.jl/pull/374, the language server sends:

```
[ Info: SENT: {"method":"workspace/configuration","id":-100,"params":{"items":[{"scopeUri":null,"section":"julia.format.indent"},{"scopeUri":null,"section":"julia.format.indents"},{"scopeUri":null,"section":"julia.format.ops"},{"scopeUri":null,"section":"julia.format.tuples"},{"scopeUri":null,"section":"julia.format.curly"},{"scopeUri":null,"section":"julia.format.calls"},{"scopeUri":null,"section":"julia.format.iterOps"},{"scopeUri":null,"section":"julia.format.comments"},{"scopeUri":null,"section":"julia.format.docs"},{"scopeUri":null,"section":"julia.format.lineends"}]},"jsonrpc":"2.0"}
```

and the `scopeUri` field cannot be null.

**Comment by davidanthoff** [comment]
So I took another look at https://github.com/julia-vscode/LanguageServer.jl/blob/de2bd4c56021529c571cce156789c8e20faa4cc5/src/protocol/protocol.jl#L20, and the more I stare at that, it probably only solves the problem when we _read_ a JSON string into a Julia structure, but not when we serialize a Julia structure into a JSON string...

I just pushed another commit to https://github.com/julia-vscode/LanguageServer.jl/pull/416/files that hopefully also fixes the write story. Could you try that branch again?

**Comment by davidanthoff** [comment]
@non-Jedi did you have a chance to test whether https://github.com/julia-vscode/LanguageServer.jl/pull/416 fixes this for you?

**Comment by non-Jedi** [comment]
I haven't yet. Will get to in next few days.
