### ISSUE TITLE
Tests are broken on master

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#435]
For example [here](https://github.com/julia-vscode/LanguageServer.jl/runs/349674368#step:5:9). I think this might be related to the new handling of empty fields in the protocol?

**Comment by davidanthoff** [comment]
And is [this](https://github.com/julia-vscode/LanguageServer.jl/blob/master/test/test_communication.jl#L9) still what we should be doing in tests, or should those elements just be removed entirely?

**Comment by ZacLN** [comment]
Yep in the first case (I've pushed a couple of commits to fix this). For your second point I don't think it matters (i.e. it falls within the protocol and is handled)

**Comment by davidanthoff** [comment]
Fixed in https://github.com/julia-vscode/LanguageServer.jl/commit/5de078d4a517c809b0e8c2b2fad86fa0c3436186 and https://github.com/julia-vscode/LanguageServer.jl/commit/380b155159f795f02d195cf60d50731110f5ee78.
