### ISSUE TITLE
Handle missing file permissions more robustly

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#450]
We have a bunch of crash reports where things go south if we don't have file permissions to read all the folders in the workspace we are trying to load. I guess we should handle those and just ignore those files?

Here are some crash reports that have this problem: [here](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%22d0a74a41-23a2-11ea-a34b-6d0bf04b3722%22%2C%22timestamp%22%3A%222019-12-21T03%3A34%3A23.479Z%22%2C%22cacheId%22%3A%22cad5061a-8b3d-4e68-a1c3-031e7604fe32%22%2C%22eventTable%22%3A%22exceptions%22%7D) and [here](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%22a8f29901-2456-11ea-aa0a-094239f94450%22%2C%22timestamp%22%3A%222019-12-22T01%3A01%3A47.601Z%22%2C%22cacheId%22%3A%2222f9f67e-6173-4d5d-a1c7-4d993832ef03%22%2C%22eventTable%22%3A%22exceptions%22%7D).

**Comment by davidanthoff** [comment]
@ZacLN is this fixed? I know you added a bunch of stuff around that?

**Comment by ZacLN** [comment]
yeps, lets try it as is for now

**Comment by ZacLN** [comment]
For ref: https://github.com/julia-vscode/LanguageServer.jl/pull/496
