### ISSUE TITLE
Option to start LanguageServer.jl as a TCP server

### ISSUE THREAD

**Issue by kdheepak** [julia-vscode/LanguageServer.jl#457]
Communication using JSON-RPC can be performed via TCP/UDP. For example, [LanguageClient-neovim allows connecting to the server using tcp](https://github.com/autozimu/LanguageClient-neovim/blob/0394fbaa2def5a5e304f7f4c08def4de4cb9e689/doc/LanguageClient.txt#L81-L84):

```
==============================================================================
2. Configuration                                 *LanguageClientConfiguration*

2.1 g:LanguageClient_serverCommands          *g:LanguageClient_serverCommands*

String to list map. Defines commands to start language server for specific
filetype. For example: >

    let g:LanguageClient_serverCommands = {
        \ 'rust': ['rustup', 'run', 'stable', 'rls'],
        \ }

In the example above, 'run', 'stable', and 'rls' are arguments to the
'rustup' command line tool.

Or tcp connection string to the server, >
    let g:LanguageClient_serverCommands = {
        \ 'javascript': ['tcp://127.0.0.1:2089'],
        \ }
```

I didn't see an issue tracking this development / discussion and thought I'd open it. This could significantly decrease the time it takes to start up LanguageServer.jl, since it can be started separately and clients can connect to an existing running instance.

**Comment by davidanthoff** [comment]
I think that should be fairly easy doable currently. You just need to pass a pipe for input and output to `LanguageServerInstance`, but that should work with both a socket or anything else.

**Comment by kdheepak** [comment]
Thanks for the answer!
