### ISSUE TITLE
Add UI for symbol server process

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#471]
We should add back some UI notification what the status of the symbol server process is. Version v3.15 seems to add support for that [here](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#progress), but it is not clear to me whether that is already shipping? If yes, can we use that? If not, should we wait until it ships, or roll our own in the meantime?

**Comment by ZacLN** [comment]
We have this?

**Comment by pfitzseb** [comment]
We do.
