### ISSUE TITLE
Remove need for julia/getFullText

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#477]
I can't help but think that [this](https://github.com/julia-vscode/LanguageServer.jl/blob/df2aa75551148785bb95e77855fb9f8dc42dd323/src/requests/textdocument.jl#L95) is only needed because we are making some mistake somewhere else? Do we really need this? I guess I don't really understand in what scenario this would be needed :)

**Comment by ZacLN** [comment]
Yep that's exactly why it's there - I couldn't work out how we'd get into that state. We could disable its use and see whether we get a flood of crashes on the alpha release?

**Comment by davidanthoff** [comment]
Yes, I think that is a good idea! We are handling updates incrementally now, right?

**Comment by ZacLN** [comment]
OK I'll disable and see what happen. 

We've been using the incremental updates for a while now
