### ISSUE TITLE
Unable to make it work with neovim

### ISSUE THREAD

**Issue by nathanielsimard** [julia-vscode/LanguageServer.jl#489]
I'm unable to make the language server run with neovim given the current documentation [here](https://github.com/julia-vscode/LanguageServer.jl/wiki/Vim-and-Neovim).

Client Logs:

```
22:28:17 ERROR reader-Some("julia") src/rpcclient.rs:35 Thread reader-Some("julia") exited with error: ErrorMessage { msg: "Unable to read from language server" }
```

Server Logs:

```
ERROR: MethodError: no method matching parse_params(::Type{Val{Symbol("textDocument/codeLens")}}, ::Dict{String,Any})
Closest candidates are:
  parse_params(!Matched::Type{Val{:initialize}}, ::Any) at /home/nathaniel/.julia/packages/LanguageServer/XXTJb/src/requests/init.jl:72
  parse_params(!Matched::Type{Val{:initialized}}, ::Any) at /home/nathaniel/.julia/packages/LanguageServer/XXTJb/src/requests/init.jl:95
  parse_params(!Matched::Type{Val{:shutdown}}, ::Any) at /home/nathaniel/.julia/packages/LanguageServer/XXTJb/src/requests/init.jl:112
  ...
Stacktrace:
 [1] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at /home/nathaniel/.julia/packages/LanguageServer/XXTJb/src/jsonrpc.jl:46
 [2] run(::LanguageServerInstance) at /home/nathaniel/.julia/packages/LanguageServer/XXTJb/src/languageserverinstance.jl:46
 [3] top-level scope at none:1
```

I also tried to make a separate julia file to run the server, but it didn't work either.

**Comment by ZacLN** [comment]
Hi, this looks to be a case of the client (neovim) sending a request fore a codeLens. We don't support that and explicitly tell the client that on connection to the server (https://github.com/julia-vscode/LanguageServer.jl/blob/master/src/requests/init.jl#L14). I think this is an issue with the neovim client - it shouldn't be sending requests that the server can't handle
