### ISSUE TITLE
Reenable an error check

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#490]
https://github.com/julia-vscode/LanguageServer.jl/blob/14e16591473c6a074ba77168f551e759ea1528fa/src/requests/features.jl#L64 needs to be fixed, as discussed in https://github.com/julia-vscode/LanguageServer.jl/pull/485#discussion_r370988266.

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/LanguageServer.jl/pull/492
