### ISSUE TITLE
We need to set a file watch system watcher for files that are added by StaticLint

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#536]
I believe StaticLint.jl can add files to `server.documents` that are outside any workspace, because it follows `include`s, right? In that case we probably need to set a file system watcher once we add such a file to the `documents` collection, so that we are notified of any changes to such a file.

**Comment by davidanthoff** [comment]
Actually, the more I'm thinking about this, I think we should _not_ follow `include`s that lead out of the current workspace. I think we could show a diagnostic on those `include`s that ideally one should include that folder in the workspace, but not do anything beyond that. Then we would have a _very_ clear story: things in the workspace get parsed, linted etc., external symbols come only via packages (symserver), and that is it.

**Comment by davidanthoff** [comment]
We can't set file system watchers outside the workspace, so for now I'm closing this.

**Comment by ZacLN** [comment]
Tbh I don't understand why that _should_ be our clear story and how it would provide any benefits?

**Comment by davidanthoff** [comment]
Probably better to discuss over at https://github.com/julia-vscode/LanguageServer.jl/issues/544, right?
