### ISSUE TITLE
Goto definition off by one line

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#540]
I'm getting a lot of goto definition targets lately that are off by 1 line. For example, here I pressed F12 on `DataFrame`, and the location shown for this is tabes.jl:23, but it should be line 22:

![image](https://user-images.githubusercontent.com/1036561/74793344-eaf79700-5274-11ea-814f-32a93bc9b532.png)

For one-line function definitions things are good. Looks to me like it might always jump to the first line of the function body right now?

**Comment by ZacLN** [comment]
To quote David Byrne: "same as it ever was". 

I don't think this is new or that we can do anything (within the current SymbolServer approach) to adjust for how Julia reports the line locations

**Comment by davidanthoff** [comment]
https://github.com/JuliaLang/julia/issues/34820

**Comment by ZacLN** [comment]
I think this has been fied upstream
