### ISSUE TITLE
Received a create notification for a file we already manage.

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#556]
From [crashreporting](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%224a28c841-5723-11ea-8a59-893ba1b01e2f%22%2C%22timestamp%22%3A%222020-02-24T16%3A32%3A31.138Z%22%2C%22cacheId%22%3A%228625c768-e82c-4bfb-985c-c2521a8bb1ce%22%2C%22eventTable%22%3A%22exceptions%22%7D).

We are hitting [this line](https://github.com/julia-vscode/LanguageServer.jl/blob/d2df108edb5b13c50fbe521c24238e30921a4dda/src/requests/workspace.jl#L16) here. The only explanation I have for this is that this file has previously been loaded already either by the parent search logic, or the static lint inlcude follow logic, right? So I imagine some kind of race situation: someone has dropped two files into the workspace, so two new create file messages are sent. While processing the first of the two, somehow during that processing it adds the second file already to our documents list (via staticlint or the parent include logic), so that when it comes around to process the second create message, it is already there. Or something like that?

I'm not sure what to do in this case... Read again from disc? Ignore the message?

**Comment by ZacLN** [comment]
What you describe sounds a likely (the only?) explanation. In any case if we're getting a Created notice then we load from disc, as we would normally?

**Comment by davidanthoff** [comment]
I was just worried that we might lose some things that way, for example if a `root` was set? The new PR I just made would preserve that because it only updates the `Document`, instead of replacing it. But I'm not sure whether that is actually the right thing to do?
