### ISSUE TITLE
Documentation of Vim and Emacs Setup Outdated

### ISSUE THREAD

**Issue by lassepe** [julia-vscode/LanguageServer.jl#596]
It seems like the documentation is outdated for vim and emas. The examples still suggest that one should handle a `Dict` as the last argument to the `LanguangeServerInstance`. However, it seems like this is a function now (error handler). Unfortunately, I don't know enough about the internals to update the documentation myself and make a PR, all I can tell is that the current documentation seems outdated.

**Comment by non-Jedi** [comment]
I've updated the Emacs documentation page to merely point at the appropriate packages. Should only be as outdated as the lsp-julia and eglot-jl packages are now. :)

**Comment by davidanthoff** [comment]
Excellent, thanks!
