### ISSUE TITLE
Default workspace/configuration to same values as vscode extension

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/LanguageServer.jl#624]
Since in the absence of a configuration value, all configuration options default to off, most non-vscode users probably aren't taking advantage of linting and formatting (or aren't aware such capabilities exist). Instead of defaulting to off, would you accept a PR that changes the default values in `request_julia_config` to [match the vs-code defaults](https://github.com/julia-vscode/julia-vscode/blob/1c50151bf7951cdf522a118bd70df2bd51425a21/package.json#L343)?

**Comment by davidanthoff** [comment]
Yes, I think so!

Something is really broken with our config story, though, I just don't know what. We get regular crash reports from VS Code that some method wasn't found etc, and taking another look at the entire config story was fairly high on my list. Maybe best if I try to solve that as part of whatever I try to fix? Or if you see something in the way we handle config that seems wrong, that would also be helpful.

**Comment by davidanthoff** [comment]
I have a slightly better sense of the config story now, and yes, I think defaulting to the VS Code default values would make sense, so a PR for that would be welcome!

**Comment by non-Jedi** [comment]
Closed by #683
