### ISSUE TITLE
Potential error

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#656]
I looked at [this](https://github.com/julia-vscode/LanguageServer.jl/blob/102915b9f8e8506dd354bd6fbdbe7e41e6220420/src/requests/textdocument.jl#L58), and I don't really understand the logic...

In particular, can't we end up in a situation here where we would delete a doc from the list that is closed but in the workspace? And that we don't ever want to do, right?

**Comment by ZacLN** [comment]
I think you're right and that
```julia
any(d.root == doc.root && d._open_in_editor for (uri, d::Document) in getdocuments_pair(server) if d != doc)
```
should read: 
```julia
any(d.root == doc.root && (d._open_in_editor || is_workspace_file(d)) for (uri, d::Document) in getdocuments_pair(server) if d != doc)
```
That is  we only remove the file-tree to which `doc` belongs if no other nodes are open or a workspace file
