### ISSUE TITLE
URI is not valid for textDocument/definition outside a package

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/LanguageServer.jl#660]
A file URI is required to be absolute as [far as I can tell](https://tools.ietf.org/html/rfc8089). Even if it isn't, the language-server client doesn't know what directory to resolve a relative file URI to.

If you create a file `main.jl`:

```julia
include("utils.jl")

lang = to_upper("julia")
```

and utils.jl:

```julia
to_upper(x) = uppercase(x)
```

And request `textDocument/definition` of `to_upper` from within `main.jl`, the URI is given as "file://utils.jl" instead of the full path that it should be:

```elisp
client-request (id:62) Tue May  5 08:00:46 2020:
(:jsonrpc "2.0" :id 62 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///home/adam/tmp/main.jl")
           :position
           (:line 2 :character 10)))

server-reply (id:62) Tue May  5 08:00:46 2020:
(:id 62 :jsonrpc "2.0" :result
     [(:uri "file://utils.jl" :range
            (:start
             (:line 0 :character 0)
             :end
             (:line 2 :character 3)))])
```

Thanks to @prasannakog for the reproducer at https://github.com/non-Jedi/lsp-julia/issues/25#issuecomment-623240065

**Comment by ZacLN** [comment]
Hiya, a couple questions to help me understand this.
- Could you elaborate a bit on what you mean by 'works inside a package' on the downstream issue? 
- Are these files saved (in the sense of having sent a `didSave` notification to the server? And if so are both files saved with a full URI?

**Comment by non-Jedi** [comment]
- If `main.jl` is instead `Main.jl` inside the `src` directory of a package (and the contents are wrapped in `module Main`), the full URI is given for `utils.jl` e.g. `/home/adam/tmp/Main/src/utils.jl`.
- Behavior is the same whether or not a `didSave` notification has been sent. When a `didSave` notification is sent, it includes the full URI:

```elisp
client-notification Tue May  5 10:29:26 2020:
(:jsonrpc "2.0" :method "textDocument/didSave" :params
          (:text "to_upper(x) = uppercase(x)\n\n" :textDocument
                 (:uri "file:///home/adam/tmp/utils.jl")))
```

**Comment by ZacLN** [comment]
As per the other issue, could you send me some logs from initialization through to the problem (maybe as a gist?)

**Comment by non-Jedi** [comment]
Here you go: https://gist.github.com/non-Jedi/fd8c9f5e31f9cac9e47d7a81d142a4b8

Thanks for taking a look. :)

**Comment by non-Jedi** [comment]
[Per report on discourse](https://discourse.julialang.org/t/emacs-based-workflow/19400/54) this is still a problem on master. I haven't personally replicated it though.

**Comment by ffevotte** [comment]
Ah, sorry, it looks like I have been too careless when doing tests: I can now confirm that this issue is indeed fixed.

I'm very sorry for the noise.

**Comment by pfitzseb** [comment]
Thanks for reporting back! :)
