### ISSUE TITLE
containerName in a SymbolInformation object should not be nil

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/LanguageServer.jl#682]
[Per the spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol), the field must be a string, but it can be omitted entirely. See #681 for an example. Similar fix to #665 I assume.

**Comment by non-Jedi** [comment]
Actually this might already be fixed by #665. I should try using a dev version of the language server to check.

**Comment by ZacLN** [comment]
Should be - all `structs` that are subtypes of `Outbound` have missing fields removed on conversion to JSON for transport
