### ISSUE TITLE
Do a round of tagging

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#685]
@non-Jedi Do you want me to do a round of tagging of packages? We don't need the tags for VS Code, so I'm always slow with that...

I would do a round of minor version bumps, I guess? Let me know if you think any of the packages should get a different version bump than that.

**Comment by non-Jedi** [comment]
A round of tagging would be wonderful. :) Unless there's breaking changes I'm not aware of the only major version bump required is for LanguageServer.jl because of #664.

**Comment by davidanthoff** [comment]
Done, they just all need to get merged in general!
