### ISSUE TITLE
Linter still not working with emacs lsp-julia

### ISSUE THREAD

**Issue by gdkrmr** [julia-vscode/LanguageServer.jl#694]
#688 fixes the crashes for me, but there is still no linting. https://github.com/emacs-lsp/lsp-mode/issues/1680  seems to indicate that `LanguageServer.jl` does not report any problems back. Could it be that some linting options are disabled?

**Comment by non-Jedi** [comment]
Could you reply with a minimal example file which should have a lint error and then the lsp-log for running the language server on that file?

**Comment by gdkrmr** [comment]
Using `lsp-julia` with Julia 1.4 on https://github.com/gdkrmr/Base58.jl does not show any errors (Other packages don't show any error either. Loading the same package with VSCode shows about a dozen.

To reproduce it, you need to use `lsp-julia` from https://github.com/gdkrmr/lsp-julia and apply #688 as a patch to the `LanguageServer.jl` that comes with `lsp-julia`.

A log can be found here: https://github.com/emacs-lsp/lsp-mode/issues/1680

**Comment by non-Jedi** [comment]
@gdkrmr Could you confirm that this error occurs with LanguageServer.jl master (with #688 applied)? I'm wondering if this was one of the bugs fixed by #717.

**Comment by gdkrmr** [comment]
I have updated all packages to match the versions in current master of the vscode plugin, then I updated LanguageServer.jl to latest master and applied #688. As before, everything works fine, except linting.

**Comment by gdkrmr** [comment]
Ok, I did some digging and I think I found the root of the issue.

- I am using master of https://github.com/gdkrmr/lsp-julia. 
- All Julia packages are in sync with `julia-vscode` v1.0.4.
- I have applied #688 

Linting does not work, because of the following:

`publish_diagnostics` [1] checks if the document is unsaved and the value of `isunsavedfile` [2] seems to be false always.

Changing the function `insunsavedfile` to:
```julia
isunsavedfile(doc::Document) = true
```
enables linting. The irony is that there even is a comment about consistency and editors :-)

Going through the message logs, URIs in `lsp-mode` always start with `"file:///"`

The question for me is how to best fix the issue:
- Is this check necessary? The code sounds as if `LanguageServer.jl` only lints unsaved documents?
- Is there a standard for this and `lsp-mode` is not adhering to it?
- If this is not standardized, where should this be fixed.

[1]  https://github.com/julia-vscode/LanguageServer.jl/blob/1048658bba9e7b9db660942d371db8627d09c062/src/requests/textdocument.jl#L313

[2]  https://github.com/julia-vscode/LanguageServer.jl/blob/1048658bba9e7b9db660942d371db8627d09c062/src/requests/textdocument.jl#L299

**Comment by gdkrmr** [comment]
I have asked on the `lsp-mode` side and it turned out that the language server had to be declared as multiroot. That solved it, thanks to everyone that contributed!

Does VSCode have a single language server process for several projects or does it open a separate process for each project?

For this to work, #688 has to be resolved, and I haven't tested the solution yet, therefore I will keep this issue open a bit longer.

**Comment by ZacLN** [comment]
Does it work with #821 which replaced #688 ?

**Comment by gdkrmr** [comment]
Just checked it and it works!
