### ISSUE TITLE
Autocompletions should not contain invalid names

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/LanguageServer.jl#719]
![image](https://user-images.githubusercontent.com/6735977/83021982-200d4580-a02b-11ea-8531-bd2186db4b4d.png)

**Comment by aviatesk** [comment]
@ZacLN, are you already on this ? I feel I want to tackle this.

**Comment by ZacLN** [comment]
Sorry - I whipped up a quick fix before I saw your message! (https://github.com/julia-vscode/LanguageServer.jl/pull/720). There's reference to another completions related issue in that PR though...

**Comment by aviatesk** [comment]
hehe, no worries, I will take a look on your PR instead ;)

> if you wanted to look at that I could give you a quick overview of it?

thanks, I will try to take a look again on the code base (maybe this weekend) and will probably ask you some questions and discuss possible enhancements/refactors then.
