### ISSUE TITLE
goto definition sometimes doesn't work

### ISSUE THREAD

**Issue by aviatesk** [julia-vscode/LanguageServer.jl#741]
Sometimes LS can offer hover (i.e. LS knows where it comes from) but can't offer `textDocument/definition`.

A random MRE:
```julia
using REPL
REPL.lookup_doc
```

**Comment by ZacLN** [comment]
Odd, that works for me - is the server response to the definition request empty?

**Comment by aviatesk** [comment]
yeah, I confirmed that works on master branch of SymbolServer or LangaugeServer ...
I initially tested this on our stable release julia-vscode.

**Comment by aviatesk** [comment]
@ZacLN let me bump again since I modified the comment

**Comment by davidanthoff** [comment]
You can set the config setting `julia.trace.server` to `verbose`, and then there is an output channel where you can see all communication between the extension and the LS. You can paste that into https://microsoft.github.io/language-server-protocol/inspector/ to get a nicer view.

**Comment by aviatesk** [comment]
Here are the logs with `using REPL; REPL.lookup_doc`:
> `textDocument/hover`
```log
[Trace - 10:02:22 PM] Sending request 'textDocument/hover - (55)'.
Params: {
    "textDocument": {
        "uri": "untitled:Untitled-1"
    },
    "position": {
        "line": 2,
        "character": 9
    }
}


[Trace - 10:02:22 PM] Received response 'textDocument/hover - (55)' in 2ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```julia\nREPL.lookup_doc is a Function.\n### 1 method for function REPL.lookup_doc\n[1] lookup_doc(ex::Core.Any) in REPL at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/docview.jl:134\n\n```"
    }
}
```

> `textDocument/definition`
```log
[Trace - 10:03:13 PM] Sending request 'textDocument/definition - (56)'.
Params: {
    "textDocument": {
        "uri": "untitled:Untitled-1"
    },
    "position": {
        "line": 2,
        "character": 10
    }
}


[Trace - 10:03:13 PM] Received response 'textDocument/definition - (56)' in 1ms.
Result: []
```

I'm on current master of julia-vscode

**Comment by ZacLN** [comment]
I think this is fixed
