### ISSUE TITLE
Unable to use Coc.nvim extension coc-julia

### ISSUE THREAD

**Issue by samueltwallace** [julia-vscode/LanguageServer.jl#751]
Hi guys, I'm trying to use [coc-julia](https://github.com/fannheyward/coc-julia) extension for Coc.nvim, but it's not working. I have no idea if it's a problem with LanguageServer.jl or with the code, but since the author of the extension hasn't gotten back to me on the extension, I figured I would try here and see if anyone has any advice.

[Issue on coc-julia](https://github.com/fannheyward/coc-julia/issues/14) - this should link to everything about the extension and my problem with it 
And since this seems to be the norm, I'll include this as well:

  "StaticLint"     => v"4.3.0"
  "LanguageServer" => v"3.0.0"
  "IJulia"         => v"1.21.2"
  "SymbolServer"   => v"4.4.0"

Also, as far as I understand typescript (which is very little), the Julia server call is [here](https://github.com/fannheyward/coc-julia/blob/master/src/ctx.ts#L86)

**Comment by non-Jedi** [comment]
This looks at a glance like the same bug as #651. #688 should fix it, but it's type piracy so hasn't been merged.
