### ISSUE TITLE
"Go to definition” doesn’t work on “using module”

### ISSUE THREAD

**Issue by BoZenKhaa** [julia-vscode/LanguageServer.jl#799]
Performing "go to definition" on module name, as in `using Combinatorics`, returns "No definition found for 'Combinatorics'" message.

**Comment by BoZenKhaa** [comment]
Hello @ZacLN, I am wondering, why was this issue closed? Is this a bad place to post feature requests such as these ?

**Comment by ZacLN** [comment]
I'm pretty sure I closed it because I added the feature!

**Comment by BoZenKhaa** [comment]
Oh nice, thanks a lot, I have just updated and it's awesome!
