### ISSUE TITLE
Being smarter about common include patterns

### ISSUE THREAD

**Issue by kcajf** [julia-vscode/LanguageServer.jl#802]
I've got a module that uses `include` to pull in some code. If I call "jump to definition" on the include statement, it gets me to the included file - great.

Once I'm in the included file, "jump to definition" doesn't work for symbols that exist in the module that the file is included into. Doing this correctly in general is obviously impossible since we can't know everwhere the file will be included. However, most modules / packages have a very simple tree structure, and most files are included only once either by a file in the same folder or one folder up. Trying to bubble up this tree a few levels, while resolving all symbols in sibling includes could be handy. Would this be difficult?

**Comment by ZacLN** [comment]
I believe this is fixed, do reopen if it persists
