### ISSUE TITLE
default env_path looks invalid.

### ISSUE THREAD

**Issue by AtsushiSakai** [julia-vscode/LanguageServer.jl#804]
Hi. Thank you for great OSS. I'm using this everyday.

When I run an instance of LanguageServer.jl without env_path like:
`julia  -e "using LanguageServer, LanguageServer.SymbolServer; runserver()"`
the language server reports installed modules as missing references.

I think this code is used for getting default evn_path ".julia/environments/v#.#":
https://github.com/julia-vscode/LanguageServer.jl/blob/91155cc204dd895df7b9e2f5e8c7edaed6ed44df/src/runserver.jl#L51
But when I run this code in my REPL, the result path is:
```
julia> Base.load_path_expand("@#.#")
"/Users/atsushisakai/.julia/environments/1.4/Project.toml"
```
But I think the path is invalid, missing "v" before the version number. I should be:
"/Users/atsushisakai/.julia/environments/v1.4/Project.toml"

When I change the code like this, I can get a correct path and the language server stopped to report installed modules as missing references
```
julia> Base.load_path_expand("@v#.#")
"/Users/atsushisakai/.julia/environments/v1.4/Project.toml"
```

Is it expected? 
If you guys accepted a small PR to fix it, let me know. I will create a PR to fix it.

**Comment by aviatesk** [comment]
@non-Jedi kind reminder

**Comment by non-Jedi** [comment]
Yep. Looks like I forgot  "v". Sorry about that, and thanks for the detailed bug report.
