### ISSUE TITLE
Upgrading LanguageServer causes a lot of downgrades for me

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/LanguageServer.jl#814]
I don't know if this is the right place for this issue, or if the issue is actually a "feature" not a bug, but when I upgrade to the latest version of LanguageServer on Julia 1.4, a lot of my packages get downgraded:

```
(@v1.4) pkg> add --preserve=none LanguageServer@3.2.0
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [46ada45e] ↓ Agents v3.3.1 ⇒ v3.1.0
  [324d7699] ↓ CategoricalArrays v0.8.1 ⇒ v0.6.0
  [a93c6f00] ↓ DataFrames v0.21.6 ⇒ v0.13.1
  [ced4e74d] ↓ DistributionsAD v0.6.3 ⇒ v0.1.1
  [da1fdf0e] ↓ FreqTables v0.4.0 ⇒ v0.3.2
  [c91e804a] ↓ Gadfly v1.3.0 ⇒ v1.2.1
  [2b0e0bc5] ↑ LanguageServer v2.0.1 ⇒ v3.2.0
  [429524aa] ↓ Optim v0.22.0 ⇒ v0.20.1
  [ce6b1742] ↓ RDatasets v0.6.9 ⇒ v0.6.1
  [2913bbd2] ↓ StatsBase v0.33.0 ⇒ v0.32.2
  [cf896787] ↑ SymbolServer v3.1.1 ⇒ v5.1.0
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [46ada45e] ↓ Agents v3.3.1 ⇒ v3.1.0
  [336ed68f] ↓ CSV v0.6.2 ⇒ v0.3.1
  [324d7699] ↓ CategoricalArrays v0.8.1 ⇒ v0.6.0
  [944b1d66] ↓ CodecZlib v0.7.0 ⇒ v0.6.0
  [34da2185] ↓ Compat v3.13.0 ⇒ v2.2.0
  [7ad07ef1] ↓ CoupledFields v0.2.0 ⇒ v0.1.0
  [a93c6f00] ↓ DataFrames v0.21.6 ⇒ v0.13.1
  [9a8bc11e] + DataStreams v0.4.2
  [ced4e74d] ↓ DistributionsAD v0.6.3 ⇒ v0.1.1
  [ffa9a821] ↑ DocumentFormat v2.1.1 ⇒ v3.2.0
  [48062228] ↑ FilePathsBase v0.8.0 ⇒ v0.9.4
  [26cc04aa] + FiniteDifferences v0.10.8
  [da1fdf0e] ↓ FreqTables v0.4.0 ⇒ v0.3.2
  [c91e804a] ↓ Gadfly v1.3.0 ⇒ v1.2.1
  [7d512f48] + InternedStrings v0.7.0
  [b9b8584e] + JSONRPC v1.2.0
  [2b0e0bc5] ↑ LanguageServer v2.0.1 ⇒ v3.2.0
  [429524aa] ↓ Optim v0.22.0 ⇒ v0.20.1
  [2dfb63ee] - PooledArrays v0.5.3
  [df47a6cb] ↓ RData v0.7.2 ⇒ v0.6.3
  [ce6b1742] ↓ RDatasets v0.6.9 ⇒ v0.6.1
  [b3cc710f] ↑ StaticLint v3.1.1 ⇒ v4.5.0
  [2913bbd2] ↓ StatsBase v0.33.0 ⇒ v0.32.2
  [cf896787] ↑ SymbolServer v3.1.1 ⇒ v5.1.0
  [f269a46b] ↓ TimeZones v1.3.1 ⇒ v0.10.5
  [9f7883ad] + Tracker v0.2.8
  [ea10d353] ↓ WeakRefStrings v0.6.2 ⇒ v0.5.8
```

Some of these downgrades are breaking, e.g., CategoricalArrays 0.6 does not work in Julia 1.4.

**Comment by davidanthoff** [comment]
Yeah, that is not a problem of LanguageServer.jl, but almost certainly just that some of your other packages is not compatible with something like the latest version of CSTParser.jl and then going back to a version of that package that does not have any dep on CSTParser.jl (or any of the other deps). Nothing we can do about that, really, these other packages just need to track the work in CSTParser.jl if they want to work with this.

Having said that, we avoid any such problems in the VS Code extension by not loading the LS into the same process that users load their code into.

For other code (like the debugger in the REPL) we use some tricks in the VS Code extension to load those packages "privately" so that the versions of the package that we need for the VS Code extension never hold back any user package installations.

**Comment by NightMachinary** [comment]
[**@David Anthoff**](https://github.com/davidanthoff) commented on [Aug 7, 2020, 1:36 AM GMT+4:30](https://github.com/julia-vscode/LanguageServer.jl/issues/814#issuecomment-670191873 "2020-08-06T21:06:05Z - Replied by Github Reply Comments"):
> Yeah, that is not a problem of LanguageServer.jl, but almost certainly just that some of your other packages is not compatible with something like the latest version of CSTParser.jl and then going back to a version of that package that does not have any dep on CSTParser.jl (or any of the other deps). Nothing we can do about that, really, these other packages just need to track the work in CSTParser.jl if they want to work with this.

Is there a way for me to find the problematic packages? I might not need them.

> Having said that, we avoid any such problems in the VS Code extension by not loading the LS into the same process that users load their code into.
> 
> For other code (like the debugger in the REPL) we use some tricks in the VS Code extension to load those packages "privately" so that the versions of the package that we need for the VS Code extension never hold back any user package installations.

So I can safely uninstall `LanguageServer` if I use VSCode?

**Comment by davidanthoff** [comment]
> Is there a way for me to find the problematic packages? I might not need them.

I think there is, but I don't know how :) Probably best to ask over at the discourse forum for help with that.

> So I can safely uninstall LanguageServer if I use VSCode?

Yes, everything that the Julia extension needs is shipped by the extension and not installed into the shared package environment, i.e. any version of LS that you install by yourself wouldn't be used by the extension in any case.
