### ISSUE TITLE
Question about arguments in LanguageServer.LanguageServerInstance 

### ISSUE THREAD

**Issue by TsuMakoto** [julia-vscode/LanguageServer.jl#815]
In Wiki: https://github.com/julia-vscode/LanguageServer.jl/wiki/Vim-and-Neovim#languageclient-neovim
`server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, "");`

In source code: https://github.com/julia-vscode/LanguageServer.jl/blob/master/src/languageserverinstance.jl#L65
`function LanguageServerInstance(pipe_in, pipe_out, env_path = "", depot_path = "", err_handler = nothing,　symserver_store_path = nothing)`

There is no argument called `debug` in the source code.
Is this a source code bug?
Or Is this a Wiki mistake?
And how will this be fixed in the future?

**Comment by non-Jedi** [comment]
The wiki is incorrect. Docstring for LanguageServerInstance should be considered authoritative. Feel free to update the wiki. :)

**Comment by TsuMakoto** [comment]
OK.
Wiki was updated.
https://github.com/julia-vscode/LanguageServer.jl/wiki/Vim-and-Neovim#languageclient-neovim

Thank you.
