### ISSUE TITLE
MethodError: no method matching Union{Int64, String}(::String)

### ISSUE THREAD

**Issue by pascal-mueller** [julia-vscode/LanguageServer.jl#836]
Hi,

trying to get this working this Coc neovim plugin. There were several issues regarding this problem but it never got solved.

## Output channel: Julia Language Server Trace

ERROR: 
[ Info: Indexing StaticLint...
MethodError: no method matching Union{Int64, String}(::String)
Stacktrace:

 [1] 
LanguageServer.InitializeParams
(
::
Dict{String,Any
}) at /home/user/.julia/packages/LanguageServer/y1ebo/src/protocol/initialize.jl:111
 [2] dispatch_msg(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.MsgDispatcher, ::Dict{String,Any}) at /home/user/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:64
 [3] 
run(::LanguageServerInstance) at /home/user/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:308
 [4] top-level scope at none:1
[Info  - 3:20:46 PM] Connection to server got closed. Server will restart.
[Error  - 3:20:46 PM] /usr/bin/julia exited with code: 1

**Comment by cqql** [comment]
I have the same issue when I precompile LanguageServer with PackageCompiler. It works fine with the default sysimage.

**Comment by oblitum** [comment]
I'm also trying to use it from coc but have hit the same issue. What does a default sysimage mean?

**Comment by oblitum** [comment]
I managed to fix this problem by [picking LanguageServer from master](https://github.com/julia-vscode/LanguageServer.jl/issues/651#issuecomment-713887759):

```julia
julia> using Pkg
julia> Pkg.add(url="https://github.com/julia-vscode/LanguageServer.jl")
julia> Pkg.add("SymbolServer")
julia> Pkg.add("StaticLint")
```
