### ISSUE TITLE
Add support for SelectionRanges request

### ISSUE THREAD

**Issue by matklad** [julia-vscode/LanguageServer.jl#838]
Please consider adding support for https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange.

In my experience as an IDE user/implementer, this is probably the most important feature to make writing code pleasant, as, combined with multiple cursors, it sort-of turns any editor into a structural editor.

**Comment by alok** [comment]
I heavily second this and would like to point out that @matklad knows his stuff.

**Comment by alok** [comment]
It would also make adding send to REPL support for things like vim trivial

**Comment by alok** [comment]
How hard would this be to implement? I have some spare time and I'd be interested.

**Comment by ZacLN** [comment]
From reading the LSP spec it looks like it'd be trivial - however, I'm not quite sure of how to trigger this request from the client or what the expected behaviour is (e.g. are parent ranges expected to correspond to the enclosing expressions?)

**Comment by alok** [comment]
@matklad?
