### ISSUE TITLE
Automatically index a new package on installation

### ISSUE THREAD

**Issue by zerefwayne** [julia-vscode/LanguageServer.jl#841]
While the Julia Language Server is running, if a new Package is added via the `] add ...` command, it is not indexed automatically. Hence, auto suggestions don't come up. To achieve this, I select Julia env again and then it indexes the package.

I would suggest that the extension watches changes in `Project.toml` and re-index automatically if necessary.

**Comment by zerefwayne** [comment]
@pfitzseb I haven't worked with a VS Code extension before. Please give some pointers about where should I start looking.

**Comment by aviatesk** [comment]
I have code to do something like this on my machine. Will post it later.

**Comment by davidanthoff** [comment]
We should really monitor `Manifest.toml` files for updates and then trigger re-indexing... But maybe after we have resolved our whole caching issues.

**Comment by pfitzseb** [comment]
We're doing that now :)
