### ISSUE TITLE
Bad JSONRPC configuration for LanguageServer.FoldingRangeClientCapabilities(::Nothing)

### ISSUE THREAD

**Issue by tel** [julia-vscode/LanguageServer.jl#844]
When attempting to load the language server in Emacs using lsp-julia, I see the following errors

```
ERROR: MethodError: no method matching LanguageServer.FoldingRangeClientCapabilities(::Nothing)
Closest candidates are:
  LanguageServer.FoldingRangeClientCapabilities(::Any, !Matched::Any, !Matched::Any) at /Users/tel/.julia/packages/LanguageServer/y1ebo/src/protocol/features.jl:217
  LanguageServer.FoldingRangeClientCapabilities(; dynamicRegistration, rangeLimit, lineFoldingOnly) at /Users/tel/.julia/packages/JSONRPC/1Kq3H/src/interface_def.jl:50
  LanguageServer.FoldingRangeClientCapabilities(!Matched::Union{Missing, Bool}, !Matched::Union{Missing, Int64}, !Matched::Union{Missing, Bool}) at /Users/tel/.julia/packages/LanguageServer/y1ebo/src/protocol/features.jl:217
  ...
Stacktrace:
 [1] LanguageServer.TextDocumentClientCapabilities(::Dict{String,Any}) at /Users/tel/.julia/packages/JSONRPC/1Kq3H/src/interface_def.jl:56
 [2] LanguageServer.ClientCapabilities(::Dict{String,Any}) at /Users/tel/.julia/packages/JSONRPC/1Kq3H/src/interface_def.jl:56
 [3] LanguageServer.InitializeParams(::Dict{String,Any}) at /Users/tel/.julia/packages/LanguageServer/y1ebo/src/protocol/initialize.jl:111
 [4] dispatch_msg(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.MsgDispatcher, ::Dict{String,Any}) at /Users/tel/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:64
 [5] run(::LanguageServerInstance) at /Users/tel/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:308
 [6] top-level scope at none:1

Process julia-ls stderr finished
```

Julia v1.5

**Comment by olynch** [comment]
I'm getting this error too.

**Comment by pfitzseb** [comment]
Hm, seems like we're expecting a `Missing` but get `nothing` instead. This might happen when the client sends `null` instead of `undefined`, which seems like a LSP violation.

**Comment by ulysses4ever** [comment]
A workaround on Emacs' side seems to be: `(setq lsp-enable-folding t)`, see [this comment](https://github.com/gdkrmr/lsp-julia/issues/23#issuecomment-613694282). It would be nice of course is this was fixed properly on either side.

**Comment by devmotion** [comment]
I don't really know what I did (some explanations [here](https://github.com/gdkrmr/lsp-julia/issues/35#issuecomment-1168101143)) but for me https://github.com/emacs-lsp/lsp-mode/compare/master...devmotion:lsp-mode:dw/fix_foldingrange seems to fix the crashes.

**Comment by devmotion** [comment]
I don't observe any crashes anymore after updating lsp-mode (contains https://github.com/emacs-lsp/lsp-mode/pull/3593) and removing the `(setq lsp-enable-folding t)` hack, it seems the problem was indeed a violation of the specs which is fixed now.

**Comment by pfitzseb** [comment]
Cool, thanks for the confirmation!
