### ISSUE TITLE
(nvim built-in lsp) Language server crashes on file save

### ISSUE THREAD

**Issue by quantum-booty** [julia-vscode/LanguageServer.jl#855]
* Nvim version: Latest nightly
* Julia, LanguageServer and SymbolServer version: Lastest

I opened an issue in nvim, and apparently the problem is related to the SymbolServer and not the nvim-lsp itself:
https://github.com/neovim/nvim-lspconfig/issues/526

## Minimal init.vim
```
call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-lua/completion-nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()

set updatetime=50
set completeopt+=menuone,noselect,noinsert
set completeopt-=preview
set shortmess+=c

autocmd BufEnter * lua require'completion'.on_attach()

lua <<EOF
require'lspconfig'.julials.setup{}
EOF

lua vim.lsp.set_log_level('error')
" log_path: ~/.local/share/nvim/lsp.log
```
## Lsp log:
There are three stages in the error log:

1) when the file is opened: First line in the log.
2) after the language server is fully loaded: From 2nd to the 9th line which ends with this text:
"[ Info: Received new data from Julia Symbol Server.\n"
3) save the file which causes the language server to crash: everything after
```
[ ERROR ] 2021-01-04T00:08:08+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	'┌ Info: Running language server\n│   env = "/home/henryw/Documents/Projects/julia-lang/julials/Project.toml"\n│   pwd() = "/home/henryw/Documents/Projects/julia-lang"\n│   project_path = "/home/henryw/.julia/environments/v1.5"\n└   depot_path = ""\n'
[ ERROR ] 2021-01-04T00:08:28+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"┌ Warning: Grisu not stored on disc\n└ @ SymbolServer ~/.julia/packages/SymbolServer/eITqF/src/SymbolServer.jl:190\n"
[ ERROR ] 2021-01-04T00:08:28+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"┌ Warning: HTTP not stored on disc\n└ @ SymbolServer ~/.julia/packages/SymbolServer/eITqF/src/SymbolServer.jl:190\n"
[ ERROR ] 2021-01-04T00:08:28+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"┌ Warning: GR_jll not stored on disc\n└ @ SymbolServer ~/.julia/packages/SymbolServer/eITqF/src/SymbolServer.jl:190\n"
[ ERROR ] 2021-01-04T00:08:28+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"┌ Warning: Latexify not stored on disc\n└ @ SymbolServer ~/.julia/packages/SymbolServer/eITqF/src/SymbolServer.jl:190\n"
[ ERROR ] 2021-01-04T00:08:28+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"┌ Warning: Artifacts not stored on disc\n└ @ SymbolServer ~/.julia/packages/SymbolServer/eITqF/src/SymbolServer.jl:190\n"
[ ERROR ] 2021-01-04T00:08:28+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"┌ Warning: LibVPX_jll not stored on disc\n└ @ SymbolServer ~/.julia/packages/SymbolServer/eITqF/src/SymbolServer.jl:190\n"
[ ERROR ] 2021-01-04T00:08:28+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"┌ Warning: Contour not stored on disc\n└ @ SymbolServer ~/.julia/packages/SymbolServer/eITqF/src/SymbolServer.jl:190\n"
[ ERROR ] 2021-01-04T00:08:29+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"[ Info: Received new data from Julia Symbol Server.\n"
[ ERROR ] 2021-01-04T00:08:58+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"ERROR: "
[ ERROR ] 2021-01-04T00:08:59+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"MethodError: no method matching send(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.NotificationType{LanguageServer.ShowMessageRequestParams}, ::LanguageServer.ShowMessageParams)\nClosest candidates are:\n  send(::JSONRPC.JSONRPCEndpoint, !Matched::JSONRPC.RequestType{TPARAM,TR}, ::TPARAM) where {TPARAM, TR} at /home/henryw/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:22\n  send(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.NotificationType{TPARAM}, !Matched::TPARAM) where TPARAM at /home/henryw/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:35\nStacktrace:"
[ ERROR ] 2021-01-04T00:08:59+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"\n [1] "
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"textDocument_didSave_notification"
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"("
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"::"
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"LanguageServer"
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	".DidSaveTextDocumentParams, ::LanguageServerInstance, ::JSONRPC.JSONRPCEndpoint) at "
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"/home/henryw/.julia/packages/LanguageServer/y1ebo/src/requests/textdocument.jl:53\n [2] "
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	'(::LanguageServer.var"#121#153"{LanguageServerInstance})(::JSONRPC.JSONRPCEndpoint, ::LanguageServer.'
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"DidSaveTextDocumentParams) at /home/henryw/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:293\n [3] dispatch_msg(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.MsgDispatcher, ::Dict{String,Any}) at /home/henryw/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:66\n [4] run(::LanguageServerInstance) at /home/henryw/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:308\n [5] top-level scope at none:12\n"```

**Comment by pfitzseb** [comment]
Turns out we're crashing while trying to show you an error message that we're about to crash...

Does this crash happen for every file you're trying to save? The error you're seeing happens because the representation of your current text document that the LanguageServer knows about is different from what's actually in the document, which is a long standing bug we've been trying to track down for a while now.

**Comment by quantum-booty** [comment]
@pfitzseb Hi, thanks for the reply. The server crashes even if I try to save an empty file. create file -> open file -> :w<CR> -> crash

**Comment by pfitzseb** [comment]
Ok thanks. I'll try to repro this locally.

**Comment by pxl-th** [comment]
I have the same issue, however, it does not happen to me with the empty file.
This is the short example on which it consistently happens to me.

**Requirements:**
- Nvim nightly
- LanguageServer master

**Steps to reproduce:**
1. Open file with the code below.
2. Wait for the `Received new data from Julia Symbol Server.`.
2. Go into insert mode, add something and save.

```julia
println("Hello!")

function add(x, y)
    x + y
end

println("Bye")
```

https://github.com/julia-vscode/LanguageServer.jl/blob/58c5ac6e908d0c95995d2e6fee0341a2d0768ff1/src/requests/textdocument.jl#L52

Then the above condition is triggered, because text in the document has trailing newline and text in the params does not.
This is consistent for me, no matter what file I open.

```
# Doc's text
println(\\"Hello!\\")\\n\\nfunction add(x, y)\\n    x + y\\nend\\n\\nprintln(\\"Bye\\")\\n
# Param's text
println(\\"Hello!\\")\\n\\nfunction add(x, y)\\n    x + y\\nend\\n\\nprintln(\\"Bye\\")
```

So I wonder if it's even LanguageServer's problem...

As for the original problem, changing 

https://github.com/julia-vscode/LanguageServer.jl/blob/f5911cbf55a72293a399107514e6fb253e257dbc/src/protocol/messagedefs.jl#L39

to 

```julia
const window_showMessage_notification_type = JSONRPC.NotificationType("window/showMessage", ShowMessageParams)
```

fixes the issue with reporting the problem.

**Comment by kdheepak** [comment]
I have the same issue with the built-in neovim lsp with the latest nightly:

```
ERROR: MethodError: no method matching send(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.NotificationType{LanguageServer.ShowMessageRequestParams}, ::LanguageServer.ShowMessageParams)
Closest candidates are:
  send(::JSONRPC.JSONRPCEndpoint, !Matched::JSONRPC.RequestType{TPARAM,TR}, ::TPARAM) where {TPARAM, TR} at /Users/USER/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:22
  send(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.NotificationType{TPARAM}, !Matched::TPARAM) where TPARAM at /Users/USER/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:35 
Stacktrace: 
 [1] textDocument_didSave_notification ( :: LanguageServer .DidSaveTextDocumentParams , :: LanguageServerInstance, :: JSONRPC . JSONRPCEndpoint) at /Users/USER/.julia/packages/LanguageServer/y1ebo/src/requests/textdocument.jl:53 
 [2] (::LanguageServer.var"#121#153"{LanguageServerInstance}) (:: JSONRPC . JSONRPCEndpoint, ::LanguageServer.DidSaveTextDocumentParams) at /Users/USER/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:293
 [3] dispatch_msg(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.MsgDispatcher, ::Dict{String,Any}) at /Users/USER/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:66
 [4] run(::LanguageServerInstance) at /Users/USER/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:308
 [5] top-level scope at none:10
```

How do I figure out why `LanguageServer.jl` is trying to crash in the first place?

**Comment by pfitzseb** [comment]
As mentioned above, 
https://github.com/julia-vscode/LanguageServer.jl/blob/58c5ac6e908d0c95995d2e6fee0341a2d0768ff1/src/requests/textdocument.jl#L52
is the right place. This could actually be an issue with the neovim LS implementation, because it appears to insert a trailing newline on save but doesn't communicate that to the LSP.

**Comment by mjlbach** [comment]
I don't *think* we're doing that, but if someone sends me a minimum file that reproduces the issue, I will make sure it's not an issue in neovim core).

**Comment by kdheepak** [comment]
@mjlbach It is failing consistently for me with this file: https://github.com/kdheepak/JuliaFormatter.vim/blob/c0fc4a1acc0d6d13cb5ff68383c6ff8952247b0b/tests/test.jl

It seems like it is failing for any Julia file except for an empty file based on an above comment.

**Comment by mjlbach** [comment]
Great, I can reproduce. Thanks, I'll look into this.

**Comment by pfitzseb** [comment]
This can definitely be fixed on our side, either by removing that check completely or by allowing differences in trailing whitespace.

**Comment by mjlbach** [comment]
@kdheepak see `:help fixeol`

try setting `set fixeol off`

By default we save with a newline

```
$
    end$
```

**Comment by quantum-booty** [comment]
I added set nofixeol to my init.vim and it still crashes on save.

**Comment by mjlbach** [comment]
Yes, `set nofixeol` seems to be broken, I'm talking with bfredl about it now. It *should* work on new buffers (not old, it doesn't strip EOL).

**Comment by quantum-booty** [comment]
hmmm it doesn't work for new buffers for me either.

**Comment by mjlbach** [comment]
Just to clarify, vim/neovim will be default fix end of lines to include the newline character, so I think for general compatibility with the vim ecosystem it would be nice if 
LanguageServer.jl ignored this. I can submit a PR if necessary.

**Comment by quantum-booty** [comment]
Why is this new line check there in the first place? If it's an empty trailing line then surely it doesn't matter.

**Comment by pfitzseb** [comment]
I think we still have a bunch of issues where the editor/LS is broken in some cases, so this was our attempt at figuring out why that's going on.
I'd still argue that the editor shouldn't make any changes to the document that aren't communicated to the LS though -- that seems potentially dangerous.

**Comment by davidanthoff** [comment]
Yes, very much agreed, I think we should stay strict and require that the editor communicates _all_ changes to the LS. And then figure out where we are still making mistakes in all of that :)

**Comment by mjlbach** [comment]
I've added a note to disable vim/neovim's default behavior (`set binary nofixeol`) for julia while using JuliaLanguageServer.jl. Fixing the end of line in this way is for POSIX compliance (and for obvious reason's vim's save behavior was never designed for keeping a client/server over RPC in sync), but it's probably not going to cause issues with Julia.

What we'd have to do on our end, is expose the c function of vim that does the end of line fixing and trigger it on an autocmd prior to saving the buffer. I doubt the PR will be accepted by vim, but maybe in neovim.

**Comment by kdheepak** [comment]
My understanding is that you tracking all the changes to the document in the internal text `String` and expecting them to match when this `didSave` notification is sent. Is that correct? I'm just curious and trying to understand what is going on here.

The section in spec for [`textDocument_didSave`](https://microsoft.github.io/language-server-protocol/specification#textDocument_didSave) has the following interfaces:

```
export interface SaveOptions {
	/**
	 * The client is supposed to include the content on save.
	 */
	includeText?: boolean;
}

interface DidSaveTextDocumentParams {
	/**
	 * The document that was saved.
	 */
	textDocument: TextDocumentIdentifier;

	/**
	 * Optional the content when saved. Depends on the includeText value
	 * when the save notification was requested.
	 */
	text?: string;
}
```

This doesn't say anything about this matching, right? What happens if some client chooses to edit the contents of `text` during save that isn't captured by another edit operation in the spec?

**Comment by mjlbach** [comment]
This issue can be closed, I worked around it in the neovim lsc client neovim/neovim#13792

**Comment by quantum-booty** [comment]
@mjlbach Thank you again, you are a legend!

**Comment by ZacLN** [comment]
Are we sure @kdheepak's interpretation above isn't correct? It makes sense to me

**Comment by mjlbach** [comment]
His interpretation is correct in that for other language server clients, you may or may not have issues depending on the save behavior. It's not defined in the spec that the version of the document internally represented by the language server and that on disk has to match.

I think the issue should be closed (or at least, renamed) because given the order of operations for saving in neovim/vim, this no longer applies.
