### ISSUE TITLE
Misclassification of client name

### ISSUE THREAD

**Issue by ZacLN** [julia-vscode/LanguageServer.jl#884]
[Azure report](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%2FresourceGroups%2FDefault%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fjulia-vscode%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%2240490a81-6a62-11eb-9bae-f530066cc390%22%2C%22timestamp%22%3A%222021-02-08T23%3A06%3A17.829Z%22%2C%22cacheId%22%3A%222e265546-0d5f-4ad8-93b6-6cb9f2eb9940%22%2C%22eventTable%22%3A%22exceptions%22%7D)

Looks like we're misclassifying a client (vscode-exploration?) as 'other' (by which I think we mean vim) when it is some version of vscode. Linked to https://github.com/julia-vscode/LanguageServer.jl/pull/881, as per that PR should we assume the client is vscode and only actively look for vim? Alternatively we could widen the code checking at https://github.com/julia-vscode/LanguageServer.jl/blob/master/src/requests/workspace.jl#L112. Either way it makes sense to put this in it's own function so that the same check is used across the package

**Comment by pfitzseb** [comment]
Why do we even need to distinguish clients there? IIUC all responses can contain any of `true`/`false`/`null`==`nothing`, so we should always fall back to our defaults for the third case, no?

**Comment by ZacLN** [comment]
I think one or other of the clients was returning `null` when it meant false? (Can't remember fully)

**Comment by pfitzseb** [comment]
Right. As per https://github.com/julia-vscode/LanguageServer.jl/pull/696 it was actually VSCode doing that. AFAICT this isn't happening anymore, so we should be good to remove this workaround.
