### ISSUE TITLE
Incorrect hint when arguments to a function are used in a Cmd

### ISSUE THREAD

**Issue by mroavi** [julia-vscode/LanguageServer.jl#903]
Minimal example:
```julia
function diff(file1::String, file2::String)
  diff_output = read(ignorestatus(`diff $file1 $file2`), String)
end
```
causes the following hints to appear:
```
Diagnostics:
1. An argument is included in a function signature but not used within its body.
2. An argument is included in a function signature but not used within its body.
```
The language server fails to detect that the arguments are being used when these are interpolated inside a `Cmd`.

**Comment by pfitzseb** [comment]
Not sure how to best handle this -- we're parsing commands correctly, but there's some custom handling for the interpolation (similar to what you could implement in any string macro). Easiest solution would be to put interpolated values somewhere into `EXPR.meta` and special case that in StaticLint. Does that sound reasonable, @ZacLN?

**Comment by untoreh** [comment]
this also happens if a variable is used inside a macro
```julia
macro dostuff()
   quote
      x = 0
   end
end

function run(x)
   @dostuff
end
```

**Comment by pfitzseb** [comment]
That's a different issue (and it's very unlikely to be solved any time soon).

The original issue is fixed, btw.
