### ISSUE TITLE
Renaming member of a kwdef struct is incorrect

### ISSUE THREAD

**Issue by Octogonapus** [julia-vscode/LanguageServer.jl#912]
I am using Julia `1.6.0-rc2` and the Julia vscode extension `v1.1.35`. Given this code:
```julia
Base.@kwdef struct Foo
    x::Int
end

foo(f::Foo) = f.x
```

Placing your cursor on `f.x` and renaming `x` to `y` works as expected:
```julia
Base.@kwdef struct Foo
    y::Int
end

foo(f::Foo) = f.y
```

However, placing your cursor on `x::Int` and renaming `x` to `y` renames the struct to `y` instead:
```julia
Base.@kwdef struct y
    x::Int
end

foo(f::y) = f.x
```

**Comment by pfitzseb** [comment]
Yeah, that happens when the cursor is in front of the `x::Int` -- `x|::Int` works fine. Will be fixed by #914.
