### ISSUE TITLE
Renaming a local variable misses instances of that variable inside inner scopes

### ISSUE THREAD

**Issue by Octogonapus** [julia-vscode/LanguageServer.jl#913]
I am using Julia `1.6.0-rc2` and the Julia vscode extension `v1.1.35`. I am not sure if this is an issue or not, but I figured I'd report it anyway. It feels like an issue to me.

Given this code:
```julia
function foo()
    x = 1
    if true
        x = 2
    end
    while true
        x = 2
    end
    for _ in 1:2
        x = 2
    end
end
```

Renaming `x` to `y` does not rename `x` inside any of the inner scopes:
```julia
function foo()
    y = 1
    if true
        x = 2
    end
    while true
        x = 2
    end
    for _ in 1:2
        x = 2
    end
end
```

Arguably, this is okay, since they could also be declarations of new local variables when looked at in isolation; however, because I already declared an `x` in an outer scope, I feel the `x`'s in the inner scopes should also be renamed.

**Comment by pfitzseb** [comment]
Yeah I think this is a bug giving Julia's scoping rules.
´
