### ISSUE TITLE
Incorrect warning: missing reference: code_warntype

### ISSUE THREAD

**Issue by mroavi** [julia-vscode/LanguageServer.jl#915]
`@code_warntype` is exported by default.

The following warning is displayed whenever I use this macro:

![image](https://user-images.githubusercontent.com/19517248/111536295-5bb7fe00-876a-11eb-8cc7-5d3733019c4c.png)

**Comment by pfitzseb** [comment]
Pretty sure that's correct unless you explicitly import `InteractiveUtils`, no?

**Comment by mroavi** [comment]
Ohh You are right @pfitzseb. I just realized that I'm importing InteractiveUtils in my startup.jl. Isn't it possible for LanguageServer to be aware of the imports in the startup.jl?

**Comment by pfitzseb** [comment]
InteractiveUtils is also automatically loaded in the REPL.
Imho linting is most useful for self-contained pieces of code (with its own environment, ideally), so I don't think we should ever look at startup.jl.

**Comment by mroavi** [comment]
I removed `using InteractiveUtils` from my startup.jl and I still see the warning.

**Comment by pfitzseb** [comment]
Yes, sure. There's no connection between the file you're currently in and startup.jl, so of course this shows up as unresolved. Why *shouldn't* it?

**Comment by mroavi** [comment]
Ok. I think I understand what you mean: `InteractiveUtils` is not exported by default like e.g. `Base`. It is actually being loaded by the REPL at startup. And the REPL is just one way of running Julia code.

So the solution to avoid the unwanted warning is to add `using InteractiveUtils` in the top of the file that is attached to the LSP server, is this right?

**Comment by pfitzseb** [comment]
Yes. You'd need to do that for a self-contained/portable script anyways.

**Comment by mroavi** [comment]
I'ts clear now. Thanks @pfitzseb .
