### ISSUE TITLE
Ignore indexing through hidden (dot-prefixed) `.folders`?

### ISSUE THREAD

**Issue by mbauman** [julia-vscode/LanguageServer.jl#920]
I'll sometimes open up a VS Code window that includes a `.julia` folder.  Parsing through my entire `.julia` takes forever!  Could we just ignore all hidden folders?  Do you already do this for `.git` folders?  Would there be common cases where parsing through a hidden folder is wanted?

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/797, basically.
