### ISSUE TITLE
Vim ALE fails in providing some completions

### ISSUE THREAD

**Issue by 00sapo** [julia-vscode/LanguageServer.jl#929]
This is just a reference for the issue I opened on ALE, hoping that someone more expert with LanguageServer can help me

https://github.com/dense-analysis/ale/issues/3695

**Comment by 00sapo** [comment]
Found that this is related to version `3.2.0`, while using `3.1.0` there are no problems... maybe we should just change to way LanguageServer is started?

Here is the command used by ALE:

```julia
using LanguageServer; 
using Pkg; 
import StaticLint; 
import SymbolServer; 

server = LanguageServer.LanguageServerInstance(
    isdefined(Base, :stdin) ? stdin : STDIN, 
    isdefined(Base, :stdout) ? stdout : STDOUT, 
    dirname(Pkg.Types.Context().env.project_file)); 

server.runlinter = true; run(server);
```

**Comment by 00sapo** [comment]
Found that Julia 1.6.0 cannot compile LanguageServer 3.1.0.
Julia 1.5.4 can safely compile LanguageServer 3.1.0 and everything works. 

With LanguageServer 3.2.0 I have the same issues with any Julia version I tried. Maybe this is the same problem as https://github.com/julia-vscode/LanguageServer.jl/issues/917

**Comment by pfitzseb** [comment]
Maybe. Do you get any error logs? I'd also try LanguageServer.jl#master (same for all dependencies).

**Comment by 00sapo** [comment]
Well, ALE has a few problems in reporting error logs from the LSP. But tried Julia 1.6 with LanguageServer#master and works.
