### ISSUE TITLE
no method matching `Union{Int64, String}(::String)`

### ISSUE THREAD

**Issue by jebej** [julia-vscode/LanguageServer.jl#941]
I am using the Sublime Text LSP client, so I am not sure exactly where the problem might lie. The server seems to start properly, and issues get highlighted properly. However, as soon as I try to click on one of the links on the popups, I get the following error:

![image](https://user-images.githubusercontent.com/11141558/119142835-e809ca00-ba14-11eb-984f-fb1378ca1708.png)

```
julials: [ Info: Indexing PrettyTables...
julials: [ Info: Received new data from Julia Symbol Server.
julials: ERROR: MethodError: no method matching Union{Int64, String}(::String)
julials: Stacktrace:
julials:  [1] LanguageServer.ReferenceParams(dict::Dict{String, Any})
julials:    @ LanguageServer C:\Users\jbejanin\.julia\packages\JSONRPC\xbAlZ\src\interface_def.jl:56
julials:  [2] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
julials:    @ JSONRPC C:\Users\jbejanin\.julia\packages\JSONRPC\xbAlZ\src\typed.jl:64
julials:  [3] run(server::LanguageServerInstance)
```

**Comment by pfitzseb** [comment]
Can you enable verbose tracing (in case the ST LC has that) to figure out what payload is sent along the `textDocument/references` request?

**Comment by jebej** [comment]
I enabled all possible logs, and this is the most info I see:

```
:: --> julials textDocument/hover(8): {'position': {'character': 18, 'line': 21}, 'textDocument': {'uri': 'file:///somefilepathIremoved.jl'}}
:: --> julials textDocument/codeAction(9): {'range': {'start': {'character': 13, 'line': 21}, 'end': {'character': 21, 'line': 21}}, 'context': {'diagnostics': [{'range': {'start': {'character': 13, 'line': 21}, 'end': {'character': 21, 'line': 21}}, 'code': 'Julia', 'severity': 2, 'source': 'Julia', 'message': 'Missing reference: uconvert'}]}, 'textDocument': {'uri': 'file:///somefilepathIremoved.jl'}}
:: <<< julials 8: None
:: <<< julials 9: []
:: --> julials textDocument/references(10): {'workDoneToken': 'wd10', 'context': {'includeDeclaration': False}, 'position': {'character': 18, 'line': 21}, 'textDocument': {'uri': 'file:///somefilepathIremoved.jl'}}
julials: ERROR: MethodError: no method matching Union{Int64, String}(::String)
```

I removed the filepath. I don't think there are issues with spaces because the rest of the server communication prior to clicking works.

**Comment by jebej** [comment]
The LS actually crashes only for the "referances" action. For "definition" it appears to return nothing:

```
:: --> julials textDocument/definition(30): {'textDocument': {'uri': 'file:///somefileIdeleted.jl'}, 'position': {'line': 27, 'character': 40}, 'workDoneToken': 'wd30'}
:: <<< julials 30: []
```

**Comment by jebej** [comment]
It looks like the server is no longer crashing with the latest version (4.0), but both the definition and the reference links still do not return anything. Is that expected?

**Comment by pfitzseb** [comment]
No. Can you share your setup so I can try this myself?

**Comment by pfitzseb** [comment]
Hm, works fine for me:

![image](https://user-images.githubusercontent.com/6735977/120030677-0f096280-bff8-11eb-8f26-a554dd7544a0.png)

 Did you make sure to update all dependencies of LanguageServer.jl?

**Comment by jebej** [comment]
Hmmm it works now, after restarting a few times.... maybe some indexing issue. Thanks for the help. I have an other error now for which I'll make a new issue.
