### ISSUE TITLE
Sysimage causing LanguageServer load to fail on Libiconv_jll

### ISSUE THREAD

**Issue by Byrth** [julia-vscode/LanguageServer.jl#950]
I use a sysimage to reduce first call / loading latency when developing. I have been using it successfully with LanguageServer for a while now, but since my last sysimage build it has been complaining that it cannot load Libiconv_jll because an artifact for it is not installed and crashing.

I can load Libiconv_jll in the container and can also load a cloned version of LanguageServer.jl at #master.

If I restore the default sysimage, everything works okay.

Any idea what could be causing this or suggestions you can give about how to avoid this problem?

**Comment by Byrth** [comment]
How do I avoid using it?

**Comment by pfitzseb** [comment]
Yep.

**Comment by Byrth** [comment]
Excellent, and those Args are ignored for LanguageServer then, I assume?

It's going to take me a bit to test, but I think I see a way to make this work.

**Comment by pfitzseb** [comment]
Yep. We like having full control over the LS process, but it's possible we'll add a setting to start the LS with a different sysimg so you can overwrite the default one.

**Comment by Byrth** [comment]
I presume I need to check `julia.useCustomSysimage` now? Is that just for when someone is using the plugin-maintained sysimage system?

**Comment by pfitzseb** [comment]
I don't think you need that if you want to manage your sysimges yourself.
