### ISSUE TITLE
Kakoune integration works only on keywords and STD modules

### ISSUE THREAD

**Issue by egolep** [julia-vscode/LanguageServer.jl#956]
As in the title, I followed the guide regarding using LanguageServer.jl with Kakoune and kak-lsp, but the result is that I get completion only for keywords and basic modules (Base, Main etc)

I am on Manjaro, kakoune v2020.09.01, kak-lsp version 10.0.0 and julia version 1.6.1

I leave here a pastebin of the kak-lsp.log file, in two the two separate cases:

using DataFrames (fails) https://pastebin.com/QtkqkzB5
using Base (works) https://pastebin.com/qEsejuRE

**Comment by pfitzseb** [comment]
Is this with LS.jl master? How are you starting the language server in Kakoune?

**Comment by egolep** [comment]
I'm using the suggested configuration (https://github.com/julia-vscode/LanguageServer.jl/wiki/Kakoune) so if I'm not getting it wrong I'm actually starting it in Kakoune

**Comment by pfitzseb** [comment]
Can you try 
```
using LanguageServer, LanguageServer.SymbolServer; runserver(stdin,stdout);
```
as the startup script instead? Also do give `pkg> add LanguageServer#master` a go if it still doesn't work.

**Comment by egolep** [comment]
Changing the startup script and using LanguageServer#master briefly worked (I got completion for DataFrames with using Da) then I closed kakoune, added more dependencies to the project and now it doesn't work again.
Moreover, it does not work for the standard environment.

**Comment by pfitzseb** [comment]
Hm, your log points to the symbol server process crashing, potentially while indexing InspectDR. Can you try removing that from your environment temporarily?

**Comment by egolep** [comment]
It now works. I did nothing other than removing the old .log file. Maybe the precompilation had some problems that re-starting kakoune solved?
Anyway, thanks for you help, suggestions and time!

**Comment by pfitzseb** [comment]
There's some startup delay, depending on how many packages you have in your environment. Glad it's working now though!
