### ISSUE TITLE
Crash on `server_ready()` command

### ISSUE THREAD

**Issue by pxl-th** [julia-vscode/LanguageServer.jl#968]
Hi. I'm experiencing LS crash each time I use `*vim.lsp.buf.server_ready()*` (here's the [doc](https://neovim.io/doc/user/lsp.html)) command to check if the server is ready.

I'm using NVim 0.6.0-dev version with the native LSP client.
Howerver, this error is not present, when using [vim-lsp](https://github.com/prabirshrestha/vim-lsp) plugin instead of the native LSP and the command (`:LspStatus`) works as intended.

Command:

```
<Cmd>lua print(vim.lsp.buf.server_ready())<CR>
```

Here's the error message:
```
ERROR: Unknown method window/progress.
Stacktrace:

[1] error(s::String)
    @ Base ./error.jl:33
[2] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ JSONRPC ~/.julia/packages/JSONRPC/yu0G3/src/typed.jl:81
[3] run(server::LanguageServerInstance)
    @ LanguageServer ~/.julia/packages/LanguageServer/66N1t/src/languageserverinstance.jl:361
[4] runserver(pipe_in::Base.PipeEndpoint, pipe_out::Base.PipeEndpoint, env_path::String, depot_path::String, err_handler::Nothing, symserver_store_path::Nothing)
    @ LanguageServer ~/.julia/packages/LanguageServer/66N1t/src/runserver.jl:46
[5] runserver()
    @LanguageServer ~/.julia/packages/LanguageServer/66N1t/src/runserver.jl:44
[6] top-level scope
    @ none:1
```

In case you want to look at the NVim config, here's the [link](https://github.com/pxl-th/dotfiles/blob/master/.vimrc#L119).
Other functionality works well, though.

**Comment by pfitzseb** [comment]
AFAICT the LSP doesn't specify `window/progress`, even though Google does turn up a bunch of results. We can of course add support for this anyways, but it would be much better if nvim were to be spec-conformant.

**Comment by pfitzseb** [comment]
Did this get fixed upstream, @pxl-th?

**Comment by pxl-th** [comment]
When using Neovim LSP there is `:LspInfo` command, that gives detailed info about client status.
So I guess, this is the command you should use, instead of the one I was using.
Although the old one `<Cmd>lua print(vim.lsp.buf.server_ready())<CR>` still crashes the server.
