### ISSUE TITLE
Using LanguageServer.jl with Helix editor

### ISSUE THREAD

**Issue by VarLad** [julia-vscode/LanguageServer.jl#982]
The julia process crashes in a second or two after starting

Take a look at https://github.com/helix-editor/helix/issues/669
There's a chance that this might be an issue on the LanguageServer.jl side of things

**Comment by archseer** [comment]
For context: The server seems to output log messages into stdout which is also used for JSON-RPC, for example: https://github.com/julia-vscode/LanguageServer.jl/blob/3093d16a287d95a99c13f1b40592c2141481c7fe/src/languageserverinstance.jl#L363

This then fails to parse on a strict parser. I recommend either disabling logging or logging to a log file.

**Comment by pfitzseb** [comment]
This shouldn't be happening on most Julia versions (logging should always go to stderr except for a few pre-release versions). 

[Enforcing that in the startup files](https://github.com/julia-vscode/julia-vscode/blob/0cc98ab1c9f546a8227a9477518ec1bbcf076f01/scripts/languageserver/main.jl#L6) is a good idea nevertheless.
