### ISSUE TITLE
False "Missing reference" in HTTP.jl

### ISSUE THREAD

**Issue by fredrikekre** [julia-vscode/LanguageServer.jl#984]
There is a warning about `Missing reference` for `common_logfmt` and `combined_logfmt` on this line: https://github.com/JuliaWeb/HTTP.jl/blob/81e8fce8377da0561f244727da0aa15b6561fff8/src/HTTP.jl#L7 but they are defined [here](https://github.com/JuliaWeb/HTTP.jl/blob/81e8fce8377da0561f244727da0aa15b6561fff8/src/access_log.jl#L114) and [here](https://github.com/JuliaWeb/HTTP.jl/blob/81e8fce8377da0561f244727da0aa15b6561fff8/src/access_log.jl#L121).

**Comment by pfitzseb** [comment]
Works fine for me. Is this on the latest released version or on master?

**Comment by fredrikekre** [comment]
Latest release, I can try master.

**Comment by pfitzseb** [comment]
Yeah, we're generally really bad about having working and up-to-date releases for all of the LS stack because the extension doesn't use the released versions anyways. Should probably automate this and push releases in lock-step or something like that...

**Comment by fredrikekre** [comment]
Fixed with StaticLint master.

**Comment by fredrikekre** [comment]
Is the VSCode running master on everything? Is that safe to do?

**Comment by davidanthoff** [comment]
We only run `master` of the packages that we "own", i.e. that are in the `julia-vscode` org, for all other packages we use the latest tagged version.
