### ISSUE TITLE
[Q] How do I query the docstring for a symbol by a string, rather than the position in the file?

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/LanguageServer.jl#986]
I want to extend the emacs UI to show the docs for Julia symbols, e.g., when showing auto-completion candidates. These candidates don't exist on the file being edited, so I can't send a hover request with a position. 

Ideally, I want to send a request that contains a string representation of a symbol (e.g., `"include"`), and get the symbol's docstring. I can also send the file position that this symbol could have been written in, but since the user has yet to type the symbol completely (it's a completion candidate), that file position won't contain the requested symbol.

PS: I am not at all familiar with LSP. I'd appreciate it if you keep that in mind. Thanks!

Related:
- https://github.com/joaotavora/eglot/discussions/744

**Comment by pfitzseb** [comment]
You can call `julia/getDocFromWord` with a `{word: "include"}` argument.

**Comment by NightMachinary** [comment]
Thanks! The output from that is quite long. Is there a way to get a more concise docstring (a one-liner would be best)? I guess not, but I thought to ask anyway. I will hack together a regex to summarize the current output if nothing better is available.

**Comment by pfitzseb** [comment]
There is not.
Auto-completion should definitely give you the docstring as the description already; if you don't see that then it's likely to be a client issue.
